### ISSUE TITLE
An I18NLoop does not return objects which have no records in the i18n table.

### ISSUE THREAD

**Issue by roadster31** [thelia/thelia#1005]
A loop which inherits I18NLoop does not return the objects which have no records in the i18n table.

Let's say I have a `carousel` and `carousel_i18n` tables. In this carousel module, the i18n information (title, description, etc.) is optional, thus, some entries in `carousel` table may not have corresponding entries in `carousel_i18n`  table.
All record which do not have a corresponding record in i18n table are not returned by the I18nLoop, at least one should exist, whatever the locale.

**Comment by lovenunu** [comment]
This is true for the front context.
If you aren't using the language strictly use and you're using backend_context="yes", it works.

**Comment by bibich** [comment]
I don't think this behavior freaky.
In the front, you could set the `force_return` argument to 1 to get the element even if it has no translation.
