### ISSUE TITLE
Can't remove a coupon from the back-office

### ISSUE THREAD

**Issue by matdev** [thelia/thelia#1034]
Delete button is missing for coupons (:

**Comment by lunika** [comment]
huhu good catch

**Comment by matdev** [comment]
On this subject, I am wondering why does the order_coupon table contain all the coupon attributes such as type, amount, etc

Wouldn't a reference to the coupon_id be enough ?

**Comment by lovenunu** [comment]
The problem is that all the order information must be always kept. If we add the delete button, people will be able to ... delete coupons. So we have to copy all the data of the coupon ( and also the product, and all the order_* tables ) on the order creation, to always have the order integrity.

**Comment by matdev** [comment]
In my opinion, the Delete button should be added, and deleting a coupon should fail when the coupon is referenced in the order_coupon table

**Comment by lunika** [comment]
a coupon can change this is why all the information are stored.

**Comment by matdev** [comment]
Good reason !
