### ISSUE TITLE
Export Prix produits hors-taxes + TTC

### ISSUE THREAD

**Issue by zzuutt** [thelia/thelia#1078]
Cela n'exporte qu'une partie des produits
pour le Hors-taxes  -> les produits d'une seule categorie
pour TTC  -> 1 seul produit

version 2.0.4 et 2.1.1

**Comment by Mertiozys** [comment]
Toujours le problème avec les dernières versions ? Je n'ai pas eu de problèmes avec le HT mais avec le TTC oui, je détaille ça ici #1610
