### ISSUE TITLE
Problème ajout super admin + édition super admin

### ISSUE THREAD

**Issue by boscorelly** [thelia/thelia#1079]
Bonjour,

lors de l'édition d'un compte super admin :
Unable to execute UPDATE statement [UPDATE `admin` SET `PROFILE_ID`=:p1, `FIRSTNAME`=:p2, `LASTNAME`=:p3, `UPDATED_AT`=:p4 WHERE admin.ID=:p5] 

lors de l'ajout d'un compte super admin :
Unable to execute INSERT statement [INSERT INTO `admin` (`ID`, `PROFILE_ID`, `FIRSTNAME`, `LASTNAME`, `LOGIN`, `PASSWORD`, `LOCALE`, `ALGO`, `REMEMBER_ME_SERIAL`, `CREATED_AT`, `UPDATED_AT`) VALUES (:p0, :p1, :p2, :p3, :p4, :p5, :p6, :p7, :p8, :p9, :p10)]

PHP Version 5.6.2

**Comment by lunika** [comment]
Bonjour,

c'est corrigé dans ce commit https://github.com/thelia/thelia/commit/a9b1db147959548dc0de284191a6b9d1ae1d5bd5 et sera intégré pour la prochaine version 2.1
