### ISSUE TITLE
TinyMCE ne marche pas

### ISSUE THREAD

**Issue by boscorelly** [thelia/thelia#1080]
Le texte saisi dans la description d'un objet n'es pas formaté.

TinyMCE n'est pas actif dans l'adminstration.

http://idmac34.com/thelia_2.1.1/web/index.php/?view=product&locale=fr_FR&product_id=2

**Comment by roadster31** [comment]
Les issues ne sont pas le lieu pour demander de l'aide ou du support. Merci d'utiliser le forum Thelia: http://thelia.net/forum

**Comment by boscorelly** [comment]
J'avais pensé que c'était un comportement anormal. Je me tourne vers le forum donc =)

**Comment by boscorelly** [comment]
Tu avais donné la réponse sur le forum :

Ouvre le fichier Tinymce.php, et remplace en ligne 28:

$this->jsPath    = __DIR__ . DS .'Resources' . DS . 'js' . DS . 'tinymce';

par :

$this->jsPath    = '..'.DS.'local'.DS.'modules'.DS.'Tinymce'.DS.'Resources'.DS.'js'.DS.'tinymce';

Ré-active ensuite le module
