### ISSUE TITLE
Error changing admin language 

### ISSUE THREAD

**Issue by griccitiello** [thelia/thelia#1083]
The following error message has been found: Unable to execute UPDATE statement [UPDATE `admin` SET `PROFILE_ID`=:p1, `LOCALE`=:p2, `UPDATED_AT`=:p3 WHERE admin.ID=:p4] 

also blank page when i try to change language in frontend (/?lang=es)

using version 2.1.1

**Comment by lovenunu** [comment]
Which version are you using ?

**Comment by griccitiello** [comment]
thelia 2.1.1 
PHP 5.4.36

**Comment by lovenunu** [comment]
The backoffice problem as been solved in 8796d38 and will be available from 2.1.2

For the front office problem, I can't reproduce it. But ```es``` isn't a valid locale as we are using xx_XX locales. :)

**Comment by griccitiello** [comment]
ok thanks, think is a problem related to sample files

**Comment by griccitiello** [comment]
do you know where to add this? it's missing when you set for example italian language as default http://awesomescreenshot.com/0f8497qo8b

**Comment by lovenunu** [comment]
It's in a the ```customer_title_i18n``` table :)

**Comment by griccitiello** [comment]
thanks! is there a way to create products importing from a list in csv file?
Do you have any sample or do I have to create a new import myself? http://doc.thelia.net/en/documentation/features/import_export/import.html

thanks again!

**Comment by lovenunu** [comment]
There is currently no product creation / import.
You can take a loop at ```Thelia\ImportExport\Import\Type``` classes. The file format is abstracted, so when you do an import, the file can be a csv, a json or an xml, there no problem until you respect the parsing format. :)
In an import handler you get the FormatterData, that contains an array of data (the parsed one), then you can do all the queries you want.

**Comment by roadster31** [comment]
> You can take a loop

So Thelia !

**Comment by griccitiello** [comment]
i'm working with a new translation: i've added portogues, but cannot translate upper navigation menu, for example the word "panier".
Not sure if it's contained in HookCart module, i've added the translation and created the php file, but looks like it's missing something from the database.. can you help?

thanks in advance

**Comment by griccitiello** [comment]
solved myself, think it was translation cache. By changing template and resetting now translation works.
