### ISSUE TITLE
Modules can't be removed from a Hook

### ISSUE THREAD

**Issue by roadster31** [thelia/thelia#1088]
In  Home / Configuration / Hooks position, it is not possible to remove a module from a Hook. When clicking the trash icon of a module, the page is reloaded, but the module is still attached to the hook.

**Comment by roadster31** [comment]
After some investigation, `RegisterListenersPass::registerHook()` always create module hooks tagged with `hook.event_listener` ìf they don't exist in the database.

Thus, deleting a tagged module hook is not possible at the moment, as such hooks are immediately re-created.

I'm thinking about adding a table (such as IgnoredModuleHooks) to store the deleted module hooks. This table will be checked by `RegisterListenersPass::registerHook()` to prevent a re-creation.

Any thoughts, guys ?

**Comment by lovenunu** [comment]
Add an "activate" column in the appropriate table would be easier :)

**Comment by roadster31** [comment]
Which table would be "appropriate" ? If you think about ModuleHook table, we will have to refactor and maybe refactor each of the ModuleHookQuery calls.

**Comment by lunika** [comment]
@roadster31 what would be the best ?

if the hook is present in your new table it is not needed to add it in ModuleHook, am I right ?

We have to create a new page for managing removed tagged module.

**Comment by roadster31** [comment]
I'll go for a new table. Deleting a module from a hook will just add the (module, hook) couple to this table. Adding again the module to the hook will remove the couple from the table.

A specific page is not required.
