### ISSUE TITLE
Hook code unicity is not checked when creating a new hook

### ISSUE THREAD

**Issue by roadster31** [thelia/thelia#1090]
When a new hook is created, Thelia doesn't check code unicity. 

For example, it's possible to create several 'home.top' hooks.

We can check unicity in the `HookCreationForm`, but we have to define a class validator, as we need both hook code and hook type fields value. Is it possible in a Thelia form ?

**Comment by bibich** [comment]
Yes, we can check this unicity with a Callback constraint.
