### ISSUE TITLE
Blog folder ID and footer links folder ID are hard coded in HookNavigation module templates

### ISSUE THREAD

**Issue by roadster31** [thelia/thelia#1095]
In main-footer-bottom.html : 

```
<nav class="nav-footer" role="navigation">
    <ul>
        {loop name="footer_links" type="content" folder="2"}
```

In main-footer-body.html : 

```
{ifloop rel="blog.articles"}
<ul>
    {loop type="content" name="blog.articles" folder="1" limit="3"}
    <li>
```

**Comment by lunika** [comment]
The only solution will be to remove this parameter and pick randomly a content ?

**Comment by roadster31** [comment]
What about putting the ID's in the variable.conf file ?

Or creating a template descriptor (juste like the module descriptors), where we can define these kind of information ?
