### ISSUE TITLE
Product combinations and associated images

### ISSUE THREAD

**Issue by griccitiello** [thelia/thelia#1098]
In combination builder you can set a different image for every combination (for example a color), but when you visit the product page and choose for a specific combination, the product image does not change to the one you've setted in builder.
Neither you see the correct image in the cart preview or during the checkout process..
Is it supposed to work this way? any clue how to fix this bug?

**Comment by lunika** [comment]
the loop allowing to display this is missing. An other issue related to this problem is open  #1122
