### ISSUE TITLE
/account generates an exception

### ISSUE THREAD

**Issue by gillesbourgeat** [thelia/thelia#1108]
Hi,

Thelia Version 2.1.1 local and http://demo.thelia.net/ 

To reproduce the bug.
User Front is disconnected.
User Back is connected

If there is an attempt to access my account (Front), 
The redirection on login does not work.
The Exception is generated.
AuthorizationException: User not granted for roles 'CUSTOMER', to access resources '' with .

**Comment by roadster31** [comment]
This issue still exists in 2.1.2, and at http://demo.thelia.net.

When logged in the back-office, trying to access /account causes the same exception :

`AuthorizationException: User not granted for roles 'CUSTOMER', to access resources '' with .`

![img-2015-06-14 15 33 38](https://cloud.githubusercontent.com/assets/2197734/8148743/e3b8d65c-12aa-11e5-9db1-e43c9e8729b2.png)
