### ISSUE TITLE
Total order amount is sometimes not calculated correctly

### ISSUE THREAD

**Issue by lopes-vincent** [thelia/thelia#1111]
I created a product with 7,21€ for TTC price that give me 6.55455€ for HT price, if I modify the TTC price in admin product and set the same price (7,21) that give me another HT price : 6.55€,
But this is not the real problem, The real problem is if I do an order with 2 of this products the total in cart is good (14,42) but when I placed the order the total amount is 14.43€.

**Comment by bibich** [comment]
Fixed by #1753 #1581
