### ISSUE TITLE
Error while activating Cheque module

### ISSUE THREAD

**Issue by thedebian** [thelia/thelia#1114]
Hi,
On an out-of-the-box install, this error message comes up while trying to activate "Chèque" module : 

```
Cannot create directory : /xx/vendor/thelia/core/lib/Thelia/Module/../../../../local/media/images/module
```

In Thelia/Module/BaseModule.php, in deployImageFolder, the path is badly resolved : 

```php
$imageDirectory = sprintf("%s/../../../../local/media/images/module", __DIR__ );
```

To fix this issue I had to replace this line with : 

```php
$imageDirectory = sprintf("%s/local/media/images/module", THELIA_ROOT);
```

Best Regards,
Pierre

**Comment by lovenunu** [comment]
Good catch, thank you !
