### ISSUE TITLE
Module informations (Title, description, .....) crushed by update module list

### ISSUE THREAD

**Issue by gillesbourgeat** [thelia/thelia#1118]
Hi,

Type : Bug, regression
Test Thelia 2.1.,1 and http://demo.thelia.net/

Change the title or description of a module and saved
Then go to the module list.
The title and description are reset

Thank you

**Comment by roadster31** [comment]
Expect a fix soon :speedboat:

**Comment by lunika** [comment]
This is fix and will be present in version 2.1.2
