### ISSUE TITLE
Missing favicon can create an error with tokens

### ISSUE THREAD

**Issue by Lucanis** [thelia/thelia#1152]
Ffter the second modification of the session token using delete/update (like on the cart page), when the {images} loop call a missing asset and find nothing, it create an error with the token.

**Comment by lunika** [comment]
I don't know if it's really a bug.

If an asset is missing, thelia will generate a 404 error but for giving you this 404, all the Thelia stack is launch again (and this is normal).

**Comment by bibich** [comment]
By default, an exception is thrown but smarty asset functions have an argument `failsafe` 
If this argument is set to 1 ( failsafe="1" ) the function fails silently when the asset is not found.
