### ISSUE TITLE
missing dependency in Thelia-project 

### ISSUE THREAD

**Issue by Alban-io** [thelia/thelia#1156]
In a new Thelia-project there is missing dependency "fzaninotto/faker", in  [setup](https://github.com/thelia/setup).

**Comment by lovenunu** [comment]
Then, it is a [thelia-project](https://github.com/thelia/thelia-project) issue :) But Thank you

**Comment by lunika** [comment]
@Alban-io are you drunk ?

**Comment by lunika** [comment]
merged #1160
