### ISSUE TITLE
It is not possible to extend Thelia core forms

### ISSUE THREAD

**Issue by roadster31** [thelia/thelia#1165]
If one want to extends a Thelia core form in a module (say, OrderPayment form) to add a field to this form (say, the 'comment' field), none of the possible methods I've found to add the 'comment' field to the form are working.

The basic idea is to subscribe to the `ORDER_BEFORE_PAYMENT` event, get the form data, read the value of 'comment' in the form data, and process the 'comment' field. To do this, we have to inject the additional 'comment' field to the standard form.

## Method 1
Create a form which extends OrderPayment, and overload the core form in the config.xml file of the plugin : 
`<form name="thelia.order.payment" class="Thelia\Form\MyOrderPaymentForm"/>`

It can't  work, as the OrderController instanciates OrderPayment, and the validation fails because the 'comment' field is present in the request, but missing in the form definition.

## Method 2
Subscribe to `TheliaEvents::FORM_BEFORE_BUILD.thelia_order_payment`, to inject the 'comment' field in the OrderPayment form. Seems fine !

Unfortunately, the `TheliaEvents::FORM_BEFORE_BUILD.*` events are generated only when a container is available in BaseForm, that is, when the caller passes the container in the constructor. The Smarty Form plugin does it, so the form is properly built in the template.
But OrderPayment controller instantiates the form like this `$orderPayment = new OrderPayment($this->getRequest());`: the container is not passed to BaseForm, and the event is not generated (sigh).
Then the 'comment' filed is not injected, and the validation fails again.

I have no other idea to extend a core form. Any suggestion ?

**Comment by lunika** [comment]
can we close this issue ?

**Comment by roadster31** [comment]
Yes !

**Comment by roadster31** [comment]
I'll have to write a HOWTO for extending core forms.

**Comment by lunika** [comment]
yes please on the documentation ?

**Comment by roadster31** [comment]
Yes. I'm adding it to the to-do list.

**Comment by joaovrodrigues** [comment]
How were you able to extend a core form? I'm looking to do this myself.
