### ISSUE TITLE
Can't change or create administrators after full install with web wizard.

### ISSUE THREAD

**Issue by rigamarole** [thelia/thelia#1181]
Hi,
I succesfully installed Thelia 2.1.1 with the web wizard locally and on a shared host as well.
But, once I logged, I've been unable to change the administrator informations (name) or create a new one.

When I tried to change the administrators' informations, I got this error :
<addr>
Unable to execute INSERT statement [INSERT INTO `admin` (`ID`, `PROFILE_ID`, `FIRSTNAME`, `LASTNAME`, `LOGIN`, `PASSWORD`, `LOCALE`, `ALGO`, `REMEMBER_ME_SERIAL`, `CREATED_AT`, `UPDATED_AT`) VALUES (:p0, :p1, :p2, :p3, :p4, :p5, :p6, :p7, :p8, :p9, :p10)]
</addr>

And when I tried to create a new administrator, I got this one :
<addr>
Unable to execute INSERT statement [INSERT INTO `admin` (`ID`, `PROFILE_ID`, `FIRSTNAME`, `LASTNAME`, `LOGIN`, `PASSWORD`, `LOCALE`, `ALGO`, `REMEMBER_ME_SERIAL`, `CREATED_AT`, `UPDATED_AT`) VALUES (:p0, :p1, :p2, :p3, :p4, :p5, :p6, :p7, :p8, :p9, :p10)]
</addr>

*As I mentioned in this thread http://thelia.net/forum/viewtopic.php?id=10940
I checked the SQL variable sql_mode which was empty.*

So, I finally came up with a solution by creating a new **Super-Admin** profile.
Then I just assigned this new profile for the main Administrator.

This trick is working well, but it looks like there's something wrong during the installation process with the wizard. 
Cause I don't understand why there is no Super-Administrator profile created and linked to the main user?

**Comment by lunika** [comment]
Hi,

this bug is already fixed and will be include in version 2.1.2.

We will probably release it next week.

Thanks

**Comment by lunika** [comment]
And if you want here is the patch : https://github.com/thelia/thelia/commit/a9b1db147959548dc0de284191a6b9d1ae1d5bd5

**Comment by rigamarole** [comment]
Great !
Thanks.

==================================

Rodolphe Besnier
Web Design & Front-End Development
— — —
mobile: +33 6 43 58 48 90
bonjour@rodolphe-besnier.com
http://www.rodolphe-besnier.com

==================================
