### ISSUE TITLE
Closed #1182 Paypal module triggers confirmation emails before payment.

### ISSUE THREAD

**Issue by rigamarole** [thelia/thelia#1182]
Which is not logical.
This issue occurs with a Thelia 2.1.1 installation.
I didn't know if previous versions' got the same issue.

**Comment by lovenunu** [comment]
Thank you for your contribution.
This is a Paypal module issue and should be on the module issues: https://github.com/thelia-modules/Paypal/issues

**Comment by rigamarole** [comment]
Oups!   :-p
I've just copied this issue in the Paypal issues' tracker.
Thanks.

**Comment by rigamarole** [comment]
Closes #1182
