### ISSUE TITLE
Product thumbnail carousel doesn't work

### ISSUE THREAD

**Issue by enurit** [thelia/thelia#1187]
When there are more than 5 thumbnails in the product page, button previous and next appears but when pushing them there's no action.

**Comment by AdeDidou** [comment]
Il manque dans le fichier product.html l'attribut carousel à div product-thumbnails :
Avant :
> <div id="product-thumbnails" class="slide" style="position:relative;">
Après correction : 
> <div id="product-thumbnails" class="**carousel** slide" style="position:relative;">

**Comment by AdeDidou** [comment]
J'ai essayé de proposer ma modification sur le code mais je ne sais pas si j'ai bien fait ce qu'il fallait...
