### ISSUE TITLE
Event TheliaEvents::AFTER_CREATECONTENT not being dispatched

### ISSUE THREAD

**Issue by ghost** [thelia/thelia#1188]
Actions listening to this event aren't being triggered. TheliaEvents::CONTENT_CREATE, however, is being dispatched. Registering for this event, however, doesn't guarantee that the Content object has been created, or am i wrong?

**Comment by lovenunu** [comment]
Contents are created in the action, so listeners are called on the event dispatch.
If you wanna be sure that the content is created in a listener, you have to plug yours after Thelia's (usually, we give our action a priority of 128, so everything <= 128 will be executed after ).
BTW, you say that actions aren't triggered, did you registered your service with the ```kernel.event_subscriber``` tag ?

**Comment by joaovrodrigues** [comment]
Yes I did register my service, and TheliaEvents::AFTER_CREATECONTENT was still not being called. When i changed it to TheliaEvents::CONTENT_CREATE, however (and without touching the xml), it was indeed called.

In any case, changing the priority will most definitely fix my issue, thanks for your reply.

**Comment by roadster31** [comment]
In fact, AFTER_CREATECONTENT is not dispatched in the controllers, where the form is directly instanciated (new SomeForm()).

This problem is fixed by PR #1173.
