### ISSUE TITLE
Less stylesheet is not wotking

### ISSUE THREAD

**Issue by m190** [thelia/thelia#1212]
Hi,
when I try to use 
```
    {* Stylesheets *}
    {stylesheets file='assets/less/styles.less' filters='less'}
        <link rel="stylesheet" href="{$asset_url}">
    {/stylesheets}
```
The page is not rendering correctly. The files are on the right places. In 2.0.4. was working ok, in 2.1.1 and 2.1.2 doesn't work.

**Comment by roadster31** [comment]
This issue is fixed by PR #1085. It will be part of 2.1.3, or 2.2.0

**Comment by micrasoft** [comment]
Hi, I've got this error when I integrate my less your changes : 
ClassNotFoundException: Attempted to load class "Less_Cache" from the global namespace in core/lib/Thelia/Core/Template/Assets/Filter/LessDotPhpFilter.php line 69. Did you forget a use statement for this class?

**Comment by micrasoft** [comment]
My bad, I forgot that : 
composer require oyejorge/less.php:~1.7
composer install --prefer-dist --optimize-autoloader

**Comment by roadster31** [comment]
:+1:
