### ISSUE TITLE
less.php cache directory ignore the environment

### ISSUE THREAD

**Issue by lunika** [thelia/thelia#1235]
The cache directory for less.php is not well configured. The folder is created in the cache directory instead of ```cache/dev``` or ```cache/prod```. Thus this cache is never removed by the ```cache:clear``` command.

**Comment by roadster31** [comment]
It is. LessDotPhpFilter.php is a listener of the TheliaEvents::CACHE_CLEAR event.

**Comment by lunika** [comment]
I didn't see this point, good to know.

But why you didn't put  it in the cache used by the kernel ?

**Comment by roadster31** [comment]
I did not care about that. I'll make the change.
