### ISSUE TITLE
Generer une nouvelle commande (cote back - thelia v2.1.2) 

### ISSUE THREAD

**Issue by zzuutt** [thelia/thelia#1248]
Bonjour,

il y a peut etre un bug au niveau de la gestion des commandes via le back
Si on passe une commande pour un client cote back
Il ne reste qu'un seul produit en stock

![10-03-2015 11-05-10](https://cloud.githubusercontent.com/assets/7439945/6575568/22338588-c730-11e4-8faa-a61bdc923d41.jpg)

le client paie par cheque
lorsque l'on passe la commande en 'paye', on a une erreur stock

![10-03-2015 11-06-15](https://cloud.githubusercontent.com/assets/7439945/6575582/38bd4df2-c730-11e4-9447-adf5255c2f20.jpg)

Apparemment lors de la generation du bon de commande, on deduit du stock et lorsque l'on passe la commande en payee cela re-deduit du stock

Dans l'onglet Livraison et facturation, une date de facturation est affichee
dans la table le champ date pour la facture est vide, vu que la commande n'est pas payee

![10-03-2015 11-16-36](https://cloud.githubusercontent.com/assets/7439945/6575588/451868a2-c730-11e4-8ef6-8884bfcdfc3b.jpg)

**Comment by lunika** [comment]
Bonjour, il faudrait ouvrir l'issue sur ce module : https://github.com/thelia-modules/OrderCreation

ainsi @Yochima sera prévenu

Merci

**Comment by zzuutt** [comment]
oups j'avais oublie que c'etait un module ... je transferts :)
