### ISSUE TITLE
Confirmation email sent before payment

### ISSUE THREAD

**Issue by griotteau** [thelia/thelia#1258]
The email is sent to the customer before he has paid.
So if the user cancel the payment (or if the payment has failed), the customer has a mail that  thanks him for his new order...

**Comment by lashus** [comment]
@griotteau I am not sure if this is an issue. The order is being placed in the store so it is only a confirmation that he has placed an order. If he has paid for the order is another matter.

There should be a second mail notifying about every order status change although it's up to the creators whether make it a part of a core or part of the module.

**Comment by griotteau** [comment]
@lashus for many people, it's an issue (including my customer ...). In the french forum, there is some post about it (for example http://thelia.net/forum/viewtopic.php?id=10941).
In others web shop that i known, the order is created only when the user has paid.

and also, in Thelia, if the payment failed, how can you pay for your order ? 
I think the order must be created only when the payment is done

**Comment by lashus** [comment]
@griotteau Well the ideal solution is to send e-mail every status change, because it's important from user side. I was actually hoping that hooks in Thelia are not only view-based. If you had for an example hook after order place or order status change - sending emails from module would be really easy. And after that you could retry payment for the same order without actually having to place new one.

So yeah - it is a bug after all, my bad. Although I'd be very happy to see controller hooks :)

**Comment by lashus** [comment]
hopefully @lunika will say a word about it in here and shed some light on the subject :) Hooks and events for basic operations are a great step forward imho and I could even write such functionality although if the main contributors won't agree to it - it's a waste of time. It requires overwriting most of the controllers so forking it further would be difficult I assume ?

**Comment by griotteau** [comment]
For now i use this workaround :

- creation a new event listener (with high prority)
   public static function getSubscribedEvents()  {                
        return array(
            TheliaEvents::ORDER_UPDATE_STATUS => 'updateOrderStatus',
            TheliaEvents::ORDER_SEND_CONFIRMATION_EMAIL => array("sendConfirmationEmail", 256),
        );
    }

-  stop the propagation in the listener
    public function sendConfirmationEmail(OrderEvent $event) {
        $event->stopPropagation();
    }

- manually send the mail
 public function updateOrderStatus(OrderEvent $event)
    {
        $order = $event->getOrder();
        if (!$order->isPaid()) return;
          ....
      $this->mailer->sendEmailToCustomer(
            'order_confirmation',
            $order->getCustomer(),
            [
                'order_id' => $order->getId(),
                'order_ref' => $order->getRef()
            ]
        );   
}

**Comment by lashus** [comment]
Well this workaround is pretty much what it should be. :) Althought according to this class, the e-mail is only sent when the order is paid.

https://github.com/thelia/thelia/blob/ea68907c1300b0846bdb85ba7a54c0637a5e600f/local/modules/Cheque/Listener/SendPaymentConfirmationEmail.php

**Comment by roadster31** [comment]
More concice and future-proof :

```
public function sendConfirmationEmail(OrderEvent $event) {
    if (! $event->getOrder()->isPaid()) {
        $event->stopPropagation();
    }
}

public function updateOrderStatus(OrderEvent $event)
{
    if (! $event->getOrder()->isPaid(true)) {
        $event->getDispatcher()->dispatch(TheliaEvents::ORDER_SEND_NOTIFICATION_EMAIL, $event);
    }
}
```

**Comment by lashus** [comment]
It's a good solution although you shouldn't hook into sendConfirmationMail. Accordingto class Order.php the email is dispatched before payment - as you said.

...
/**
     * @param OrderEvent $event
     */
    public function orderBeforePayment(OrderEvent $event)
    {
        $event->getDispatcher()->dispatch(TheliaEvents::ORDER_SEND_CONFIRMATION_EMAIL, clone $event);
        $event->getDispatcher()->dispatch(TheliaEvents::ORDER_SEND_NOTIFICATION_EMAIL, clone $event);
    }
...

So you should hook into **TheliaEvents::ORDER_BEFORE_PAYMENT** and stop sending email. Also hook **ORDER_AFTER_PAYMENT** and send then email :)

**Comment by roadster31** [comment]
Be careful in 2.1.2 and before about stopPropagation(). Have a look to PR #1244 .

**Comment by roadster31** [comment]
> So you should hook into TheliaEvents::ORDER_BEFORE_PAYMENT and stop sending email.
No, as the shop manager should receive the order notification.

**Comment by lashus** [comment]
@roadster31 True for brackets but also you can stop sending the email to customer with sending a notification to admin :) Still, there are a lot of solutions to this.

I agree about brackets :) I have a strange day and troubles with collecting thoughts.
