### ISSUE TITLE
Language change issue

### ISSUE THREAD

**Issue by lashus** [thelia/thelia#1261]
Hello,

I'm new to thelia, currently discovering its features although I have ran into severe issue - the language doesn't change or changes partially. For example - I choose language as french and some form fields are translated, some are not but top navigation bar or menu labels are not translated at all for any language.

Anyone has ran into similar problem?

**Comment by roadster31** [comment]
Doesn't change *at all* or change *partially* ?

**Comment by lashus** [comment]
Language changes but the translations appear partially.

**Comment by roadster31** [comment]
This is probably due to a wrong or missing translation domain in the modules.

Could you please put here a screenshot showing the problem ?

**Comment by lashus** [comment]
I doubt it's the module because it affects whole backend. Screenshot below.

![screenshot_1](https://cloud.githubusercontent.com/assets/3299478/6615842/d889c13a-c8a7-11e4-99da-d217158505f4.png)

**Comment by roadster31** [comment]
Ho, you're talking about the back-office.

La,guages are working for ages in the back-office, and we have no issue reported. Please go to the forum to get support: http://thelia.net/forum

**Comment by lashus** [comment]
Ok thanks - must be issue from my side, just checking up with you. Thanks for help.

**Comment by roadster31** [comment]
Thanks !
