### ISSUE TITLE
Creating new translations - mockup data

### ISSUE THREAD

**Issue by lashus** [thelia/thelia#1263]
Hello,

I am currently working on Polish translation for thelia software and I am wondering whether updating sql installation file to import new language (add record to table lang) and import modules and hooks translations (along with other things like Polish taxes) is recommended?

**Comment by lunika** [comment]
@bibich is working on a new process about the sql transalations in PR #1246 this will help a lot your work if you want to add your translations.

**Comment by lashus** [comment]
@lunika I don't have a problem with it - I was just wondering how should I prepare it If i want to share it with community ;) And should I put it into main repo?

**Comment by lovenunu** [comment]
@lashus Yes, please do your PR on ```thelia/thelia```, other repos are read-only as they are automaticly updated from this repo.
Thanks a lot for your contribution.
