### ISSUE TITLE
Paypal US Account > State is required

### ISSUE THREAD

**Issue by hubombing** [thelia/thelia#1279]
Bonjour,
Faisant un test de paiement Paypal en tant que faux client américain, j'ai rencontré une erreur, cad l'apparition de la page "gotopaypalfail.html".

Les log de Paypal informe que l'état est manquant :
17: INFO [PaypalApiLogManager.php:logTransaction()] {59} 2015-03-16 17:04:00: 2015-03-16 16:04:00 Transaction Failure correlationId: 3da19670a1a2c error: [10729] <Shipping Address State Empty> The field Shipping Address State is required 

Le pb est le même que ce soit "USA - New York" ou "USA - Alabama", etc...
Le fameux champ state si cher aux ricains doit aussi poser problème pour les clients canadiens...
Oups, ça ne semble pas être un bug mais une lacune, state est laissé vide...

Thelia 2.1.2
Module Paypal/Controller/GotoPaypal.php ligne 137 :

```$setExpressCheckout->setCustomerDeliveryAddress(
  $address->getLastname(),
  $address->getAddress1(),
  $address->getAddress2(),
  $address->getCity(),
  "", // State
  $address->getZipcode(),
  CountryQuery::create()->findPk($address->getCountryId())->getIsoalpha2()
);

**Comment by lovenunu** [comment]
Bonjour, merci d'avoir remonté ce problème.
Je pense qu'il aurait plus sa place dans les issues du module Paypal: https://github.com/thelia-modules/Paypal/issues

**Comment by hubombing** [comment]
C'est juste !
https://github.com/thelia-modules/Paypal/issues/17
