### ISSUE TITLE
We should be able to override a form success_url

### ISSUE THREAD

**Issue by lovenunu** [thelia/thelia#1285]
I think that we should be able to override a success url for a more fluid navigation.
For example, if someone is on the cart page and tries to checkout, we redirect him to the login page, and when he's logged in, he goes back on the home page.

If there was a query parameter on the redirection that defines the success url to ```/order/delivery```, he's only have to login that checkout.

Here's the flow:
- The user is on the cart page
- He's redirected to ```/login?success_url=%2Forder%2Fdelivery```
- He logs in
- He's redirected to ```/order/delivery``` instead of ```/```

This could be extended to all the forms.

**Comment by lunika** [comment]
c'est pas faux.

**Comment by lovenunu** [comment]
![drogue](https://cloud.githubusercontent.com/assets/6106094/6711247/147cb868-cd86-11e4-8c99-c34303b80cf0.gif)

**Comment by roadster31** [comment]
> he's only have to login that checkout.
he only have to login, then checkout ?

**Comment by lovenunu** [comment]
he only have to login, then checkout ?

Yes !

**Comment by pierr0t** [comment]
I don't understand, why does it go back to home ? here it goes directly to delivery.
