### ISSUE TITLE
Problème procédure de changement de mot de passe

### ISSUE THREAD

**Issue by pierr0t** [thelia/thelia#1291]
Bonjour,

Comme évoqué ici: thelia.net/forum/viewtopic.php?pid=64928

Quand on fait une procédure de changement de mot de passe, on va sur un écran password, on saisit son email, on reçoit un email avec un nouveau mot de passe, on est redirigé vers la page login, jusqu'ici c'est bon. A partir de là, on resaisit son login (email) et le nouveau mot de passe reçu, on est loggué (donc ça marche) sauf qu'on est redirigé vers la page password de nouveau. La plupart des gens ne font pas attention et ne voient pas qu'ils sont bien loggués ... se retrouvant sur cette page password, ils pensent que ça n'a pas fonctionné et recommencent. ... et là ça part en vrille ...

Comme expliqué sur le forum, par moi et par d'autres, on a bien la déclaration
```{set_previous_url ignore_current="1"}``` qui devrait empêcher l'enregistrement de la page password comme étant une "previous url" ... marche pas ...

Plaintes quasi quotidiennes de mes clients, il faut dire que ça semble une fonction essentielle et très usitée, personne ne semble capable de gérer ses mots de passe.

Tout ça en 2.1.2.

**Comment by lunika** [comment]
Thelia enregistre les redirections.

Je vais faire une PR qui enregistre les url uniquement si il s'agit d'une réponse en success

**Comment by lunika** [comment]
le problème est réglé dans c7087f4d1524a6052c03b2ec2b94bee73c766261 et sera dispo dans la prochaine version 2.1
