### ISSUE TITLE
Erreur lors de la désinstallation d'une module

### ISSUE THREAD

**Issue by Kira-kyuukyoku** [thelia/thelia#1302]
En cochant la case "Delete also module data" avec le module activé, on obtient le message suivant : The module "Yo" is currently in use by at least one order, and can't be deleted.

Pourtant les fichiers sont bien supprimer du serveur mais la désinstallation cotê SQL ne s'est pas faite.
Tester uniquement avec le module Yo. Je suis à la version 2.1.2 de Thelia.

En image:
http://www.casimages.com/i/150323041903164566.png
http://www.casimages.com/i/150323041903387587.png

Edit:
Nouveau test sur une nouvelle installation sans rien d'installer et j'ai tenter de désinstaller le module carousel sans cocher la case cette fois et module désactiver. J'obtient le même message et pourtant les fichiers sont bien supprimer quand même.

http://www.casimages.com/i/150323050050912938.png
http://www.casimages.com/i/150323050052429537.png

**Comment by bibich** [comment]
This issue has been fixed in #1166
However, SQL tables created by a module are not deleted by Thelia and it's the reponsability of the module to implement this in the `destroy` function of the main module class.
