### ISSUE TITLE
Inconsistency in virtual product processing.

### ISSUE THREAD

**Issue by roadster31** [thelia/thelia#1306]
The default template allow the customer to put a virtual product in his cart, whatever the stock of this product is, and whatever the value of 'check-available-stock' is.

A problem occurs when the order is paid: if check-available-stock is 1, the Order action will check the stock, and redirect the user to the cart page without any notice if the stock of a virtual product is 0.

So we have to decide if we process the stock of a virtual product a) like concrete products (thus preventing the customer to put them in cart), or b) as an infinite stock.

Any thoughts ?

**Comment by zzuutt** [comment]
I was asking itself the same question
I think that it would be necessary to add a variable
by example :  check-available-stock-virtualproduct
true -> concrete product
false -> infinite

**Comment by roadster31** [comment]
IMO, this is not enough, as we may have in the same catalog some virtual products with an infinite stock, and other with a limited stock.

Maybe we have to integrate this feature to virtual products.

**Comment by zzuutt** [comment]
Ok I understand
I think we should use the same variable, same behavior to all products

**Comment by bibich** [comment]
This issue is fixed in #961.
By default, it does not use the stock. But you can change this behavior in a module (event: TheliaEvents::VIRTUAL_PRODUCT_ORDER_HANDLE)
