### ISSUE TITLE
Minify files in web directory only

### ISSUE THREAD

**Issue by matdev** [thelia/thelia#1317]
The file templates/frontOffice/default/assets/css/styles.css is minified, making it difficult to read.

It would be nice to minify it in the web directory only.

**Comment by roadster31** [comment]
This file is not intended to be red by humans. It is generated by the compilation of the various less files located in the "assets/less" directory; assets/less/style.less is the starting point.

You'll get somme support about less in the Thelia forum, [here] (http://thelia.net/forum/viewtopic.php?id=10885), for example, and in some other places.

**Comment by matdev** [comment]
Thanks for this

**Comment by lunika** [comment]
Can I close this issue ?
