### ISSUE TITLE
Copy js files into web directory automatically

### ISSUE THREAD

**Issue by matdev** [thelia/thelia#1318]
Currently, one have to write code so that a module's js files are copied across the web directory.

Is it possible to have these files automatically copied across ? 
(It seems to be the case with css files already)

**Comment by lovenunu** [comment]
You can use the ```{javascripts }``` function as explained here: http://doc.thelia.net/en/documentation/templates/assets.html#{javascripts}

**Comment by roadster31** [comment]
In fact, you have to use `{javascripts}` function.

**Comment by matdev** [comment]
The problem is that our module's js depends on jQuery.
When we use {javascripts} function, the code is executed before jQuery is loaded, which generates error

**Comment by lovenunu** [comment]
You have to use this function in the provided blocks. You can use ```after-javascript-include```, ```javascript-initialization``` or ```javascript-last-call``` in back office context.

Those blocks are placed after jQuery inclusion, so you don't have any dependency problem ;)

**Comment by miguel30032015** [comment]
the problem is the code injection is before the block statement, so when js code is included this issue always persist   and that even if is we use the block after-javascript-include, javascript-initialization.
there is another solution ?
