### ISSUE TITLE
Tax rule builder is not working at all.

### ISSUE THREAD

**Issue by roadster31** [thelia/thelia#1333]
It is not currently possible to create a new tax rule, all the work done in the "Taxes" tab is not saved.

**Comment by lovenunu** [comment]
Ho ... I hope it's an april fool !

**Comment by roadster31** [comment]
Unfortunately, no. Check by yourself.

**Comment by lunika** [comment]
Which version of Thelia do yo use ? 2.1.2 ? Did you test it on master branch ?

I test it and I don't have problem, I can create a new tax rule and then edit it, changing taxes and countries.

Maybe it is a particular case ? Is it a percentage tax or fixed amount ? etc ?

Thank you.

**Comment by lunika** [comment]
The last modification made about TaxRules is this one : https://github.com/thelia/thelia/commit/babc451d2769c073ceb83bb5ce0e5ebcf24ca355

**Comment by roadster31** [comment]
I've tested it on the master branch. I'll try again after a reset_install.

**Comment by roadster31** [comment]
After reset_install, the tax rule builder is working again.
