### ISSUE TITLE
Absolute path for log is a problem

### ISSUE THREAD

**Issue by driou** [thelia/thelia#1334]
This is a not a good way to set the path containing the Thelia's logs with the Absolute path, it makes a lot of side problems during deployment or migration.
Is there a way to use relative path?  (using the DocRoot reference)

**Comment by driou** [comment]
New releases ... Nothing new about my issue ?

**Comment by lovenunu** [comment]
It'll come, don't worry

**Comment by lunika** [comment]
There are lot of issues open, be patient.
