### ISSUE TITLE
Tax shipping

### ISSUE THREAD

**Issue by bepascal** [thelia/thelia#1350]
It is impossible to have the tax on the shipping costs in the loop order.
To comply with regulations it's important to display postage without tax and VAT.

**Comment by lovenunu** [comment]
The order loop now has 4 outputs for shipping:
- POSTAGE
- POSTAGE_TAX
- POSTAGE_UNTAXED
- POSTAGE_TAX_RULE_TITLE

Your problem seems resolved :)
