### ISSUE TITLE
Order export fails when the shop has (not so) many orders

### ISSUE THREAD

**Issue by roadster31** [thelia/thelia#1352]
The basic order export function is exporting ALL orders. For a shop with around 1500 orders, the export fails with an OutOfMemoryException.

**Comment by lovenunu** [comment]
Well ... then we should add a filter option, as now we have a hook to handle that :D

**Comment by roadster31** [comment]
Maybe find a way to lower memory usage, so that all orders can be exported.

**Comment by lovenunu** [comment]
I've got an idea ... but, it's PHP 5.5 only and it's called generators.

**Comment by roadster31** [comment]
Tsss... Be creative !

**Comment by lovenunu** [comment]
Send the file to the client by writing it directly through a socket ? :D

**Comment by roadster31** [comment]
Well, use disk buffers instead of memory. Otherwise the feature brecomes quickly unusable: some of my customers get more than 2000 orders a month.

**Comment by lovenunu** [comment]
The real solution would be a generator and generator delegation ```yield from $generator();```, but it's PHP 7 only... :cry:

**Comment by roadster31** [comment]
The real solution is using the disk instead of the memory.

**Comment by roadster31** [comment]
IMO, the issue shoud not be closed, as the main issue (memory used by the export framework) is not solved by using a date range.

What about all customers of a high-selling shop ? Or some complex custom exports ?

What if I want to export orders for a month ?
Even if a date range could be defined, some data still can't be exported. For example all customers, or s

**Comment by gillesbourgeat** [comment]
I have a solution. but for the 2.3.

**Comment by roadster31** [comment]
What is this solution ?

**Comment by roadster31** [comment]
I'm reopening this issue, as it is not possible to export customers from a shop with around 17.000 customers, as not enough memory is available, while memory_limit is set to 512M...

As the minimal requirements are now PHP 5.5, why don't we use generators and streamed responses to prevent memory problems ?

**Comment by zorn-v** [comment]
What the problem was use "streamed responses" before 5.5 ?
I'm answer - there is no differense, coz "streamed response" just "echo" while doing job. Problem with server (nginx, apache etc) which actually send response. Many several "timeouts" and other "buffer" settings on different layers.
Don't forget how PHP works.

Anyway I'm don't understand how "generators and streamed responses" help with this...

**Comment by roadster31** [comment]
I believe I know how PHP works :) The problem with exports on a big database is caused by storing huge arrays in memory. Generators allow "mutliple returns" from inside a function (check yield() to have an idea of how generator works). Instead of building a huge array which is "echoed" it in the response, you can get the results one by one, and write them to the response buffer, or in a temporary file to allow zipped responses.

No more arrays, no more memory problems. 

Got it ?

**Comment by lopes-vincent** [comment]
The exports as been rewamped since this issue, and I just did a test, I managed to export 80000 orders without problem
