### ISSUE TITLE
Coupons product / category

### ISSUE THREAD

**Issue by Vyndi** [thelia/thelia#1373]
A percentage discount coupon for a specific product will be applied on the price including taxes
A percentage discount coupon for an entire category will be applied on the price without taxes

**Comment by lunika** [comment]
Both have the same behaviour. The discount is applied on the price without tax.

**Comment by Vyndi** [comment]
Rectification : 
- A percentage discount coupon for a specific product will be applied on the price without taxes
- A percentage discount coupon for an entire category will be applied on the price without taxes
- A percentage discount coupon for the entire cart will be applied on the price including taxes

**Comment by lunika** [comment]
I gave a solution in #1379
