### ISSUE TITLE
Impossible to stay connected in front office and back office

### ISSUE THREAD

**Issue by mylo85** [thelia/thelia#1386]
Tested with Thelia 2.1.3

If i am connected in front office, it's impossible to be connected in the back office in the same time with the same browser's session.

It's not practical for back-office's users who want's to preview their front-office. 

![oops](https://cloud.githubusercontent.com/assets/10974835/7231513/ee7d25f8-e775-11e4-9a5a-32950697803e.png)

**Comment by lovenunu** [comment]
In fact, you can. The problem is that ```/admin``` is kind of blocked when you're connected in the front.

You have to access ```/admin/login``` to log in the back office
