### ISSUE TITLE
Cellphone missing on order detail page

### ISSUE THREAD

**Issue by mespeche** [thelia/thelia#1394]
In the Delivery & Billing tab on order detail page (backoffice), the cellphone is missing :

![capture d ecran 2015-04-23 a 09 55 35](https://cloud.githubusercontent.com/assets/2156044/7292776/f5bd4d22-e99e-11e4-9df8-8100ba23e2cf.png)

**Comment by lovenunu** [comment]
In fact, the cellphone is not saved on order creation. The table ```order_address``` doesn't have any cellphone column.

**Comment by lovenunu** [comment]
Fixed by #1421
