### ISSUE TITLE
A language cannot be deleted if it is referenced by an order

### ISSUE THREAD

**Issue by roadster31** [thelia/thelia#1400]
When trying to delete an language, the following error is displayed if this language is referenced in the order table.

`Propel\Runtime\ActiveQuery\ModelCriteria::delete is unable to delete.`

The exception cause is :

`SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`thelia2`.`order`, CONSTRAINT`fk_order_lang_id`FOREIGN KEY (`lang_id`) REFERENCES`lang`(`id`))`

We have to remove this constraint (which, BTW, doesn't exists in the customer table).

**Comment by lovenunu** [comment]
We already talked about this. I think that the solution is to create an ```order_lang``` table to always keep all the data of every order.

**Comment by roadster31** [comment]
:+1:

**Comment by lovenunu** [comment]
Ohhh, I already posted an issue for that Oo #644 Let's close one of the two issues :)

**Comment by bibich** [comment]
This issue is partially fixed by #1832 
Language has now two flag `active` and `visible` to display it in  back and front. So we're not obliged to delete it to hide it in the front.

**Comment by roadster31** [comment]
I dot not really agree. A Thelia admin should be able to completely delete a language. @lovenunu gave the proper solution to this problem.

**Comment by lopes-vincent** [comment]
Same issue as #1145, the order table should not have any foreign keys on a table that does not belong to the order.
