### ISSUE TITLE
Sales management issues

### ISSUE THREAD

**Issue by lunika** [thelia/thelia#1426]
if products related to a sale are deleted, it's not possible to remove or disabled a Sale.

**Comment by lunika** [comment]
This append when an import script (faker.php or import.php) is used because foreign_keys_checks is disabled.

**Comment by roadster31** [comment]
So we juste have to fix the faker, aren't we ?

**Comment by lunika** [comment]
Yes, It's done I have to push it and create a PR

**Comment by lunika** [comment]
Done in #1428
