### ISSUE TITLE
Install on populated database does not let choose the db  

### ISSUE THREAD

**Issue by doekia** [thelia/thelia#1432]
During database selection a prepopulated database cannot be selected (disabled)
Next step poorly fail w/ "No database selected"

**Comment by lunika** [comment]
And what do you want ?

**Comment by doekia** [comment]
? No database selected because we cannot choose one is a normal behaviour ?

I expect either a message stating "Database not empty - installation stopped!"
Or a checkbox asking for database overwrite - I prefer this one - since it may well be that we install on a database already containing tables.

**Comment by lunika** [comment]
If you don't select a database how can we display like "Database not empty - installation stopped!" ?

We decided to not allow the installation of Thelia in a populated database. But you can create a new one if your user has access granted for that.

**Comment by doekia** [comment]
You miss the point here.
The page does NOT ALLOW database selection (we enter credential), but allow NEXT.
It is just confusing for end users
