### ISSUE TITLE
web/order/invoice page

### ISSUE THREAD

**Issue by pamperop** [thelia/thelia#1443]
web/order/invoice "change address" link is http://www.xxxxx.com/web/order/invoice# so it is not going to change address.

**Comment by lovenunu** [comment]
This link is a javascript trigger that shows the other customer's addresses ( as he may have many ones in his address book ).
They are hidden by default, but with a bit of javascript, they are revealed and can be chosen as a radio input.

**Comment by pamperop** [comment]
ahh allright then
