### ISSUE TITLE
Currency symbol position for  £ and AUD$

### ISSUE THREAD

**Issue by gaetanMX** [thelia/thelia#1445]
Hello,
I'm currently working for an Australian customer and I would like to format the prices (AUD$) like this : 
"$2,495.00"
But I didn't find how to change the symbol currency position. Any help would be appreciated. 
I tried to use "en_GB" for language locale.
Best regards, 

Gaetan

**Comment by roadster31** [comment]
Github issues are not the place to get support. Please use the [Thelia forum] (http://thelia.net/forum) for this purpose.
