### ISSUE TITLE
Cannot change currency symbol position

### ISSUE THREAD

**Issue by roadster31** [thelia/thelia#1446]
The currency symbol position is hardcoded in core/lib/Thelia/Tools/MoneyFormat.php: `$number = $number . ' ' . $symbol; `

The symbol position (or even the complete money format) should be a per-langage configuration parameter.

**Comment by bojanz** [comment]
It's not just the symbol position, it's also whether there's a space between the number and the symbol, the decimal separator, the grouping separator, the size of the primary and secondary digit groups.
All of this is per locale.

Thelia can require the intl extension and use its NumberFormatter class, or ship the CLDR data and reimplement the formatter like [commerceguys/intl](https://github.com/commerceguys/intl) did.
