### ISSUE TITLE
Create static pages

### ISSUE THREAD

**Issue by cellulosa** [thelia/thelia#1480]
is there a way to create static pages and add them to the menu?

**Comment by lunika** [comment]
You mean if Thelia can generate static pages ?

**Comment by cellulosa** [comment]
yep. Otherwise in order to that should I create a new view-controller? And should I do it on a new bundle?

**Comment by roadster31** [comment]
The issues are not the place to get support. Please use the [Thelia forum](http://thelia.net/forum) for this purpose.

**Comment by cellulosa** [comment]
I see. Ok, thank you!
