### ISSUE TITLE
Email templates empty lines are aways stripped

### ISSUE THREAD

**Issue by roadster31** [thelia/thelia#1498]
When an email template is created or updated in the Back-Office, all empty lines are stripped, which is ennoying for the plain text version of the message

Before form validation :

![img-2015-06-16 12 49 52](https://cloud.githubusercontent.com/assets/2197734/8181450/534daaac-1426-11e5-80fe-9ad2918c017e.png)

After form validation : 

![img-2015-06-16 12 50 08](https://cloud.githubusercontent.com/assets/2197734/8181453/5ee514f4-1426-11e5-98f4-f358256f92b1.png)

This is also true for the HTML version.

**Comment by lunika** [comment]
Solved in #1508
