### ISSUE TITLE
There's no way for and administrator to retrieve a lost password

### ISSUE THREAD

**Issue by roadster31** [thelia/thelia#1510]
Thus, a negligent administrator wiil be locked out the back-office !

A way to solve this problem would be to store the administrator email address in its profile data, and implement the same password reset process as in the front office.

**Comment by lunika** [comment]
I know it is a missing feature but this kind of feature scared me

**Comment by roadster31** [comment]
The idea of beeing locked out the BO is much more scary.

Even wordpress provides a password reset system. Wordpress.

**Comment by bibich** [comment]
If you have access to the command line you can generate a new password : `php Thelia admin:updatePassword <login>`

**Comment by roadster31** [comment]
Sure, but if you don't, you're stuck.
