### ISSUE TITLE
Thelia and PHP 7

### ISSUE THREAD

**Issue by lunika** [thelia/thelia#1515]
Thelia is not ready to run with PHP7.

To do that we have to : 

- migrate to symfony 2.7, symfony/debug component in version 2.3 doesn't work with PHP 7 (because ExceptionEngine doest not extends \Exception https://wiki.php.net/rfc/engine_exceptions_for_php7)
- migrate to last PHPUnit version

I don't think all of this work can be done in Thelia 2.2, so the first version compatible with PHP 7 will be Thelia 2.3

**Comment by gillesbourgeat** [comment]
:+1:

**Comment by whyte624** [comment]
:+1:

**Comment by gillesbourgeat** [comment]
Hello,
Thelia 2.3 was migrated to Symfony 2.8.
This issue will be closed.
