### ISSUE TITLE
Max File Size for upload

### ISSUE THREAD

**Issue by pierr0t** [thelia/thelia#1532]
I opened a discussion in the forum about a file size problem when uploading a document:

http://thelia.net/forum/viewtopic.php?pid=66339

My server is properly set to accept files up to 64MB (upload_max_filesize    64M) and this has been confirmed with a phpinfo() test.
When trying to upload a 19mb pdf file in the "document" tab of content, I instantaneously receve a "File is too big" popup stating that the limit is 8MB. I receive this message even if I am disconnected from the internet ... this shows that this is most probably a javascript message, not a PHP message ...

When analyzing the source code, I find some js:
`Dropzone.prototype.defaultOptions = {`
`maxFilesize: 256,`
`dictFileTooBig: "File is too big ({{filesize}}MB). Max filesize: {{maxFilesize}}MB.",`

and furher down (lines 4724 and also 4938):
`var imageDropzone = new Dropzone("#images-dropzone", {`
`            dictDefaultMessage : $('.btn-browse').html(),`
`            uploadMultiple: false,`
`            maxFilesize: 8,`
`            acceptedFiles: 'image/png, image/gif, image/jpeg'`
`       }); `

So it seems to me (and Roadster31 agrees ...) that this is a bug in the Dropzone configuration ... This is a Thelia 2.1.2 setup.
Pierre.

**Comment by lunika** [comment]
True and this was removed in PR #1389 and is present in version 2.1.4

**Comment by pierr0t** [comment]
Sorry, not being very familiar with the github language ... does this mean that I can install 2.1.4 to fix it ? (the way you say it I feel like it was fixed in #1389 but reapparead in 2.1.4) ....

**Comment by lunika** [comment]
sorry, it is fixed and the patch is present in version greater or equal than 2.1.4.

You can take the patch and apply it if you want, it is only 2 lines to remove.
