### ISSUE TITLE
Add the choice of template to product creation

### ISSUE THREAD

**Issue by gillesbourgeat** [thelia/thelia#1560]
Add the choice of template to product creation
Default value : the template of the parent category

**Comment by roadster31** [comment]
I don't undersand. Could you be more specific ?

**Comment by gillesbourgeat** [comment]
Example :
![sans titre-1 copie](https://cloud.githubusercontent.com/assets/7335734/8615112/319ea41a-26f0-11e5-9703-c5d48e9f517a.jpg)

**Comment by roadster31** [comment]
The View plugin (https://github.com/AnthonyMeedle/thelia-modules-View) offers a complete solution to assign specific views to specific products, contents, categories and folders (and their children).

Maybe integrating this plugin into the core will be a good ides ?
