### ISSUE TITLE
Store configuration

### ISSUE THREAD

**Issue by Vyndi** [thelia/thelia#1595]
In the BO, if the field "Email addresses of notification recipients *" is empty, it's impossible to order a product.

Error message : Address in mailbox given [] does not comply with RFC 2822, 3.6.2.

**Comment by lunika** [comment]
It will be great to ask this information during installation process and put this field as mandatory.

**Comment by gillesbourgeat** [comment]
The problem is already fixed
https://github.com/thelia/thelia/blob/master/web/install/end.php#L68-L70

**Comment by lovenunu** [comment]
I had this error once on a Debian 7/php 5.5.12, and it wasn't because it was empty, but because the PREG extension was completely broken and returned false even for a valid address.
The same error message was displayed ```Error message : Address in mailbox given [] does not comply with RFC 2822, 3.6.2. ```

IMHO it had to be said.
