### ISSUE TITLE
Setting form data in session breaks coupon

### ISSUE THREAD

**Issue by Alban-io** [thelia/thelia#1597]
Hi,

I'm working currently in Thelia beta 2.2.

When i render a coupon update template (/admin/coupon/update/{$id}) my php session is broken because :

In the [ParserContext::addForm() method](https://github.com/thelia/thelia/blob/master/core/lib/Thelia/Core/Template/ParserContext.php#L124), when adding form data in session there is a problem because the Coupon condition classes all extends [ConditionAbstract](https://github.com/thelia/thelia/blob/master/core/lib/Thelia/Condition/Implementation/ConditionAbstract.php#L42) which contains [BaseFacade](https://github.com/thelia/thelia/blob/master/core/lib/Thelia/Coupon/BaseFacade.php#L40) which contains application container (this object is unserializable and can not be serialized) !

**Comment by lunika** [comment]
These objects in session is a real problem, if it's possible, I suggest to remove this feature while thelia 2.2 is not stable.

**Comment by roadster31** [comment]
Then we have to find a clean and robust way to process invalid forms, and pass them to the template engine. 

Using  the session is not perfect, but it's working in most cases.

**Comment by gillesbourgeat** [comment]
You want to retrieve the forms after a redirection or you just want automatically inject the forms in parser context if there is an error ?

**Comment by roadster31** [comment]
As we have no standard way to process form errors, specially in front office, getting firm context after a redirection is *very* handy.
