### ISSUE TITLE
Read more link not translated for English

### ISSUE THREAD

**Issue by maxpaynestory** [thelia/thelia#1621]
When i logged in to back office home on bottom there are button for read more. Text of buttons are not translated to english.
![screen shot 2015-08-09 at 11 25 55 pm](https://cloud.githubusercontent.com/assets/462460/9157053/bffb92b6-3eee-11e5-967e-e7d8b3ef7125.png)

**Comment by Mertiozys** [comment]
Thanks, this will be fixed in Thelia 2.2 :-)
