### ISSUE TITLE
installing extensions

### ISSUE THREAD

**Issue by ackmedikal** [thelia/thelia#1622]
Sorry, an error occurred: Unable to guess the mime type as no guessers are available (Did you enable the php_fileinfo extension?)
The module zip file * :
Your module should be packaged in a zip file.
continuous error  
What is the solution

**Comment by gillesbourgeat** [comment]
Hello,
In a terminal, enter the command ```php -m```
See if ```fileinfo``` is present.

**Comment by gillesbourgeat** [comment]
Hello,
This issue is pending since too long, no responses given to questions. It will be closed.
Thank you for your understanding.
