### ISSUE TITLE
Pagination Next Prev Limit issue

### ISSUE THREAD

**Issue by m190** [thelia/thelia#1623]
Hi,

I noticed some issues in pagination. The first one is the Next - Prev issue: if you try to go to the second page in category, and then back to first page, and repeat this some more time and you will get an URL like this: http://localhost/thelia-trunk/web/index_dev.php/?category_id=1&limit=12&locale=en_US&page=1&page=2&page=2&view=category&page=1

The second issue is when you are on send page, but you choose such amount of items per page, which will could be shown only on one page. Then you will get a page with warning no items. The correct behavior should be redirect on the prev page, or not redirect, but correct URL generation from the beginning.

Thanks,

Alexandr

**Comment by gillesbourgeat** [comment]
Thanks you for your issue
