### ISSUE TITLE
Implement a system of state / province

### ISSUE THREAD

**Issue by bibich** [thelia/thelia#1638]
For now, states / provinces are saved in the country in Thelia. So there are as many countries as there are states. (ex : USA - California, USA - Alabama, ...)
Instead we should manage state / province in a separated model that will be linked to country.

**Comment by InformatiqueProg** [comment]
Good idea,
just one thing if you touch this.
Some times for delivery, we need more information than the country like state or zip code.
Actually the function getPostage only get the country value...
