### ISSUE TITLE
There's no (zero) hooks in default email template.

### ISSUE THREAD

**Issue by roadster31** [thelia/thelia#1660]
We should provide the same kind of hooks in the email templates as in the PDF template.

**Comment by InformatiqueProg** [comment]
:+1:

**Comment by InformatiqueProg** [comment]
Is there somebody working on it ?
If not, say to me, i 'll try

**Comment by gillesbourgeat** [comment]
Hello,
You can try. Wilt thou that i assign you this request ?

**Comment by roadster31** [comment]
:+1:

**Comment by InformatiqueProg** [comment]
Ok, i'll do this
@gillesbourgeat has you wan't
