### ISSUE TITLE
Problem with Module install via composer

### ISSUE THREAD

**Issue by driou** [thelia/thelia#1670]
I tried to instal several modules via composer like this and I always have the same problem like this (example with atos-module)
php composer.phar require thelia/atos-module
Using version ^1.0 for thelia/atos-module
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install thelia/atos-module 1.0.1
    - Conclusion: remove thelia/installer 1.0
    - Installation request for thelia/atos-module ^1.0 -> satisfiable by thelia/atos-module[1.0, 1.0.1].
    - Conclusion: don't install thelia/installer 1.0
    - thelia/atos-module 1.0 requires thelia/installer ~1.1 -> satisfiable by thelia/installer[1.1, 1.2].
    - Can only install one of: thelia/installer[1.1, 1.0].
    - Can only install one of: thelia/installer[1.2, 1.0].
    - Installation request for thelia/installer == 1.0.0.0 -> satisfiable by thelia/installer[1.0].

I think there's a problem with the version of thelia/installer.

**Comment by driou** [comment]
I'm under 2.2.0-beta3 version but it's the same under 2.1.5. I think the problem is that lot of modules requires thelia/installer:~1.1 and last versions of thelia use version 1.0

**Comment by lunika** [comment]
Thelia doesn't require thelia/installer so the problem is not in Thelia. One of its dependencies is maybe out-of-date or the composer.lock was not updated cleanly.

**Comment by bcabarrou** [comment]
This may be caused by a module that has a too strict version requirement for `thelia/installer`.
