### ISSUE TITLE
dealer  install

### ISSUE THREAD

**Issue by ackmedikal** [thelia/thelia#1683]
plugin gives error
Where errors
An error occured
Unable to execute SELECT statement [SELECT dealer_tab.ID, dealer_tab.COMPANY, dealer_tab.ADDRESS1, dealer_tab.ADDRESS2, dealer_tab.ZIPCODE, dealer_tab.CITY, dealer_tab.COUNTRY, dealer_tab.DESCRIPTION, dealer_tab.SCHEDULE, dealer_tab.PHONE_NUMBER, dealer_tab.WEB_SITE, dealer_tab.LATITUDE, dealer_tab.LONGITUDE, dealer_tab.CREATED_AT, dealer_tab.UPDATED_AT FROM `dealer_tab` LIMIT 1]

**Comment by gillesbourgeat** [comment]
Refer : https://github.com/thelia-modules/Dealer/issues/1
