### ISSUE TITLE
Wrong form field values when updating an administrator

### ISSUE THREAD

**Issue by roadster31** [thelia/thelia#1685]
When updating an administrator, the update form fields are not properly filled : 

![img-2015-09-17 15 26 12](https://cloud.githubusercontent.com/assets/2197734/9934321/c827506c-5d50-11e5-809a-3d3ba3731d0a.png)

Thelia 2.2.0-beta3

**Comment by gillesbourgeat** [comment]
This bug will be fixed in stable version 2.2

**Comment by roadster31** [comment]
Thanks ^^
