### ISSUE TITLE
new customer registry errors

### ISSUE THREAD

**Issue by ackmedikal** [thelia/thelia#1691]
![1](https://cloud.githubusercontent.com/assets/3216298/9977382/611662ea-5f0e-11e5-9a3f-d793f9bc844b.png)

**Comment by gillesbourgeat** [comment]
Hello, 
It's possible to have the error details by adding index_dev.php in your url .
Example : mysite.com/register => mysite.com/index_dev.php/register
Your ip address should be present in the file index_dev.php, for a remote access.

**Comment by bibich** [comment]
Do you still have the issue ?

**Comment by gillesbourgeat** [comment]
Hello,
This issue is pending since too long, no responses given to questions. It will be closed.
Thank you for your understanding.
