### ISSUE TITLE
Virtual products and documents

### ISSUE THREAD

**Issue by senn77** [thelia/thelia#1703]
Hello,

It would seem is not possible to choose 1 document by language in the virtual products module. If I select an other document in an other language, it still keep the default document.

Thank you.

**Comment by bibich** [comment]
You can't do this in default implementation. You have to implement this feature in a new module, add an UI in back office to link your document to the right language and then customize the download of  the file in listening the event `TheliaEvents::VIRTUAL_PRODUCT_ORDER_DOWNLOAD_RESPONSE` (something like in `local/modules/VirtualProductDelivery/EventListeners/VirtualProductEvents.php`)
