### ISSUE TITLE
coupon issue in thelia

### ISSUE THREAD

**Issue by rajeevswe** [thelia/thelia#1705]

**Comment by rajeevswe** [comment]
how can i fix this coupon related issue we are getting error page when adding coupon code to redeem

**Comment by roadster31** [comment]
Please give us more details.

What were you doing ? What is the version of your Thelia ?

**Comment by rajeevswe** [comment]
i am using Thelia 2.2.0.

I have created a coupon code from admin tools section and apply it with on of the product and enter code and click on ok button then this error will appear.

Thanks.

**Comment by rajeevswe** [comment]
Basically i want to use thelia for eCommerce  project just i was checking its feature that i got this issue.

**Comment by rajeevswe** [comment]
So when i expect this problem has been resolved and i can start use of it or need to download another version of thelia?

**Comment by roadster31** [comment]
Do we have a couple of hours ?

**Comment by rajeevswe** [comment]
sure

**Comment by rajeevswe** [comment]
hi roadster31 why have u removed your comment from this post?

**Comment by rajeevswe** [comment]
as you mention 

Do we have a couple of hours ?

So what was that?
