### ISSUE TITLE
Wrong micro datas price and condition for a product

### ISSUE THREAD

**Issue by ThomasArnaud** [thelia/thelia#1741]
Hi,

it seems that the price tag in the product template is not valid because of the price currency that shouldn't be present in the tag.
Moreover when the landing page is not in English, the price has to be specified with a period as a decimal separator and not a comma. It is not the case for the French page for example.
I don't know what the problem is with the condition.

You can verify it with the google testing tool here : https://developers.google.com/structured-data/testing-tool/

**Comment by gillesbourgeat** [comment]
Resolved by #1974

![structured data testing tool google developers](https://cloud.githubusercontent.com/assets/7335734/14210854/3611bb9c-f82b-11e5-8451-3c5606aff5b0.jpeg)

**Comment by Asenar** [comment]
:)
