### ISSUE TITLE
Category and Product SEO url can't work?

### ISSUE THREAD

**Issue by benyang2015** [thelia/thelia#1756]
on backend,the category seo url is 'http://mywebsite.com/test-category.html',
on frontOffice,the category url is 'http://mywebsite,com/?view=category&lang=en_US&category_id=1',
how the solve the problem?

**Comment by gillesbourgeat** [comment]
Hello,

The configuration variable 'rewriting enabled' has value at 1 ?

http://mywebsite.com/admin/configuration/variables

**Comment by benyang2015** [comment]
Thanks @gillesbourgeat

**Comment by roadster31** [comment]
Issues are not the place to get support. Please use the Thelia forum : http://thelia.net/forum
