### ISSUE TITLE
Wrong content for "delivery-module-list-block" in "order-delivery.html"

### ISSUE THREAD

**Issue by InformatiqueProg** [thelia/thelia#1775]
For example : a customer with 2 address
for this cart, he choose the second address (not the default address) and go on "order invoice"
Customer forgot a product, go back to cart or what you want
When he see the "order delivery" a second time, the default address is selected, but AJAX call don't give the address selected and he will have a module list for the second address...

**Comment by bibich** [comment]
It has been fixed  in version 2.3.0-alpha1

Now the selected address is stored in session when customer change it.
