### ISSUE TITLE
Rewriting URL

### ISSUE THREAD

**Issue by m190** [thelia/thelia#1777]
When rewriting URL is enabled and the item has a SEO URL defined, it's page couldn't be addressed anymore in a normal way (for example with ?view=product&locale=en_US&product_id=1)!!!

**Comment by gillesbourgeat** [comment]
Hello,

The configuration variable 'rewriting enabled' has the value 1 ?

........................./admin/configuration/variables

**Comment by m190** [comment]
Hi,

yes
