### ISSUE TITLE
Shipping zone only shows countries, that are alreay associated with a shipping zone

### ISSUE THREAD

**Issue by madc** [thelia/thelia#1809]
Version: 2.2.1

The country list on the shipping zone management page in backoffice only contains countries that are already associated with a shipping zone. If you empty the `country_area` table, there seems to be no way of adding countries to a shipping zone, as the list is empty. Also, if a country is associated with two shipping zones, it appears twice in the list.

**Comment by bibich** [comment]
Fixed in version  2.3.0-alpha1
