### ISSUE TITLE
[API] Add product categories endpoint 

### ISSUE THREAD

**Issue by jmaupetit** [thelia/thelia#1812]
I wonder if there was a `/api/categories/` endpoint. If it exists, it's unfortunately not documented :(

**Comment by lunika** [comment]
It exists but it is not documented... unfortunately

**Comment by bibich** [comment]
It's documented now http://doc.thelia.net/en/documentation/api/routes/category.html
Thanks

**Comment by jmaupetit** [comment]
:+1:
