### ISSUE TITLE
Dashboard statistics in December are not shown

### ISSUE THREAD

**Issue by m190** [thelia/thelia#1828]
If you open the dashboard http://demo.thelia.net/admin you will see that there is no any graph. If you look at debug network console, there is a request `stats?month=0&year=2016&flush=0` which is incorrect. Instead of it should be a `month=12` and `year=2015`.

**Comment by gillesbourgeat** [comment]
Hello,

This problem will be fixed in the version 2.2.2.

The solution, if you want fix the bug : https://github.com/thelia/thelia/pull/1824

Best regards.
