### ISSUE TITLE
Colissimo shipping zones has changed

### ISSUE THREAD

**Issue by jodeq** [thelia/thelia#1863]
When I update my shipping price with the last collisimo pricing I see that shipping zones from colissimo has changed.
Here the pdf : http://www.colissimo.fr/particuliers/envoyer_un_colis/decouvrir_loffre_colissimo/Tarifs_colissimo/att00002941/PDF_Tarifs2015_AELGP_DepartFranceMetropolitaine.pdf

Would you like if I provide for you the new shipping zones in thelia with the right prices ?

Regards.

**Comment by bibich** [comment]
Thanks. Yes, it would be great to provide us the new configuration :+1: 
You can do it in a new Pull Request. More info on how to proceed here : http://doc.thelia.net/en/documentation/contribute.html#pull-request

Thanks

**Comment by jodeq** [comment]
PR is merged.
This issue could be closed

**Comment by bibich** [comment]
thanks
