### ISSUE TITLE
bug admin 'form 'thelia.lang.default_BEHAVIOR' doesn't exist'

### ISSUE THREAD

**Issue by neywen** [thelia/thelia#1873]
I get a 'form 'thelia.lang.default_BEHAVIOR' doesn't exist' error when selecting 'strictly use the requested language' from the 'Languages and URLS' administration page.

Here is what I do to reproduce the problem:
- download a fresh new thelia 2.2.1
- install it using the wizard, requesting 'french' for both 'admin language' and 'shop language'
- create a test product
- activate 'colissimo' module
- create a customer account
- add the test product to my cart
- display the cart content

in the backoffice:
- go to the Configuration tab
- choose 'Languages & URLs' item
- select 'strictly use the requested language' from the dropdown list 'If a translation is missing or incomplete:'
- click 'save'

=> error.

**Comment by gillesbourgeat** [comment]
Hello,
This bug is fixed on the master branch.
The fix will be applied to version 2.2.2
Best regards,

https://github.com/thelia/thelia/pull/1821
https://github.com/gillesbourgeat/thelia/commit/2329ace7c82f9b30b819cad7768616fa1958c29b

**Comment by neywen** [comment]
I took a look to the issue list before posting this one, but I apparently missed it, sorry for that.
Thanks for the answer.
l.
