### ISSUE TITLE
Add  Listener to Adminsitratori_create

### ISSUE THREAD

**Issue by abertranb** [thelia/thelia#1930]
Hello I want to add a custom event subscribed to TheliaEvents

``const ADMINISTRATOR_CREATE                    = "action.createAdministrator";``

Is it possible? I have to create a new module? any suggestion? 
Could you send me a link to do that

I think we have to add a custom Listener like (Symfony version)

``$listener = new AcmeListener();``
``$dispatcher->addListener('foo.action', array($listener, 'onFooAction'));``

Thanks!

**Comment by roadster31** [comment]
Issues are not the place to get support. Please use the Thelia support forum: http://thelia.net/forum

**Comment by abertranb** [comment]
Sorry!

**Comment by roadster31** [comment]
:)
