### ISSUE TITLE
Can't update Thelia 2.2.1 with Thelia v2.2.2 (web update)

### ISSUE THREAD

**Issue by InformatiqueProg** [thelia/thelia#1934]
il me dit :
"Il semblerait que Thelia soit déjà installé sur ce serveur. Merci de vérifier la configuration et d'apporter les corrections nécessaires avant de ré-essayer. "

Le problème vient du fichier ``` thelia/core/lib/Thelia/Install/Update.php ```
La version 2.2.1 est 2 fois et pas de de 2.2.2
        '39' => '2.2.1',
        '40' => '2.2.1',

**Comment by Asenar** [comment]
Oui c'est ça, et ça peut être corrigé par #1940 

Sinon le fix "rapide" c'est de remplacer `2.2.1` par `2.2.2`

On en a parlé ici : http://thelia.net/forum/viewtopic.php?pid=69129#p69129
