### ISSUE TITLE
ability to sort product in each category

### ISSUE THREAD

**Issue by Asenar** [thelia/thelia#1941]
Currently, the product position is determined by the field `product.position` and concern only its main category. it would be more flexible if a product could be positioned differently in each category, so merchant can use a different default order in each categories, putting products forward according to their needs (the default theme does not show "default sorting" but it can be easily added)

Current workaround (without coding) is to create the main category containing all products, and then adding others category as "secondary". But this make some mess in the backoffice product lists.

**Comment by bibich** [comment]
This issue already exists *since a long time*. see #132
