### ISSUE TITLE
Composer warning "dependencies will break in the future" : `composer-plugin-api:1.0.0` 

### ISSUE THREAD

**Issue by gmichard** [thelia/thelia#1979]
Today, a `composer install` display the following message : 

```bash
$ composer install -o
The "thelia/installer" plugin requires composer-plugin-api 1.0.0, this *WILL* break in the future and it should be fixed ASAP (require ^1.0 for example).
[...]
```

The versions of these dependencies should be updated.

**Comment by bcbrr** [comment]
For reference, as of Composer 1.1.0, this finally breaks. Any project with a dependency somewhere on `thelia/installer` version 1.1 or earlier should be affected. Modules should be updated to use `thelia/installer` in at least version 1.2 to prevent this.
