### ISSUE TITLE
feature with free_text_value is not stored in the right place

### ISSUE THREAD

**Issue by zzuutt** [thelia/thelia#2011]
the free_text_value is stored in Table: `feature_av_i18n`
field `title` type varchar(255)
![pasted_image_at_2016_02_24_15_46](https://cloud.githubusercontent.com/assets/7439945/13289817/aa88fefe-db11-11e5-9f77-13e196c257a1.png)

**Comment by roadster31** [comment]
This is the proper place as the free text values should be internationalized.
