### ISSUE TITLE
[Bug] Oubli de classes

### ISSUE THREAD

**Issue by TBreard** [thelia/thelia#2024]
Bonjour,

Dans le fichier category.html (et dans tout les fichiers comportant une toolbar, comme le includes/toolbar.html), il manque les classes btn-grid et btn-list aux boutons correspondant qui permettent de changer le mode de vue du catalogue.

Sans ces classes, on peut par exemple cliquer sur le bouton grille alors qu'on est déjà en mode grille et ainsi passer en mode liste.

**Comment by gillesbourgeat** [comment]
Thanks for your issue !
