### ISSUE TITLE
Delivery module methods don't get the delivery address, just the delivery country

### ISSUE THREAD

**Issue by roadster31** [thelia/thelia#2025]
Delivery module methods `isValidDelivery()` and `getPostage()` don't get the delivery address, just the delivery country, making impossible (or *very* complicated) the calculation of zip-based shipping costs.

**Comment by gillesbourgeat** [comment]
The pull request https://github.com/thelia/thelia/pull/1985 does not solve your problem ?

**Comment by roadster31** [comment]
Yes, but as far as I know, it is not yet documented in the Thelia doc.

Without a proper documentation, this feature does not exists, as nobody (except some happy few) knows it is availabe.

**Comment by gillesbourgeat** [comment]
Yes, you right
An issue has been created on the documentation repository.
https://github.com/thelia/thelia.github.io/issues/213

**Comment by roadster31** [comment]
Thanks
