### ISSUE TITLE
[2.2.2] ClassNotFoundException when updating a module

### ISSUE THREAD

**Issue by roadster31** [thelia/thelia#2029]
Thelia 2.2.2 : when trying to update a module by uploading the zip file, the following errors occurs : 

![img-2016-03-07_10-23-49](https://cloud.githubusercontent.com/assets/2197734/13565189/d264bc38-e44e-11e5-9bac-f7ad0a33cb89.png)

**Comment by gillesbourgeat** [comment]
Fixed by #2100
