### ISSUE TITLE
Bug - Change of position of an image of module

### ISSUE THREAD

**Issue by zzuutt** [thelia/thelia#2040]
``Propel\Runtime\Exception\BadMethodCallException: Call to undefined method: changeAbsolutePosition. in D:\wamp\www\Thelia222\core\lib\Thelia\Model\Base\ModuleImage.php on line 2064 Call Stack #TimeMemoryFunctionLocation 10.0180140456{main}( )..\index.php:0 20.17602915128Symfony\Component\HttpKernel\Kernel->handle( ???, ???, ??? )..\index.php:38 30.382010112096Stack\StackedHttpKernel->handle( ???, ???, ??? )..\Kernel.php:188 40.382010112224Thelia\Core\Stack\SessionMiddleware->handle( ???, ???, ??? )..\StackedHttpKernel.php:23 50.459014480808Thelia\Core\Stack\ParamInitMiddleware->handle( ???, ???, ??? )..\SessionMiddleware.php:80 60.460014481968Thelia\Core\TheliaHttpKernel->handle( ???, ???, ??? )..\ParamInitMiddleware.php:87 70.460014482624Symfony\Component\HttpKernel\HttpKernel->handle( ???, ???, ??? )..\TheliaHttpKernel.php:80 80.460014482856Symfony\Component\HttpKernel\HttpKernel->handleRaw( ???, ??? )..\HttpKernel.php:61 90.588016631432call_user_func_array:{D:\wamp\www\Thelia222\core\vendor\symfony\http-kernel\Symfony\Component\HttpKernel\HttpKernel.php:117} ( ???, ??? )..\HttpKernel.php:117 100.589016631712Thelia\Controller\Admin\FileController->updateImagePositionAction( ???, ??? )..\HttpKernel.php:117 115.420316649152Thelia\Controller\Admin\FileController->updateFilePositionAction( ???, ???, ???, ??? )..\FileController.php:735 129.830617514200Thelia\Controller\BaseController->dispatch( ???, ??? )..\FileController.php:713 139.830617514224Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch( ???, ??? )..\BaseController.php:115 149.831617515304Symfony\Component\EventDispatcher\EventDispatcher->dispatch( ???, ??? )..\ContainerAwareEventDispatcher.php:167 159.831617515512Symfony\Component\EventDispatcher\EventDispatcher->doDispatch( ???, ???, ??? )..\EventDispatcher.php:53 169.831617515712call_user_func:{D:\wamp\www\Thelia222\core\vendor\symfony\event-dispatcher\Symfony\Component\EventDispatcher\EventDispatcher.php:164} ( ???, ??? )..\EventDispatcher.php:164 179.831617515752Thelia\Action\BaseCachedFile->updatePosition( ??? )..\EventDispatcher.php:164 1811.292617529280Thelia\Action\BaseAction->genericUpdatePosition( ???, ??? )..\BaseCachedFile.php:269 1932.259817610920changeAbsolutePosition ( ??? )..\BaseAction.php:40 2032.259817611224Thelia\Model\Base\ModuleImage->__call( ???, ??? )..\BaseAction.php:40``

**Comment by gillesbourgeat** [comment]
Thanks for your issue !
