### ISSUE TITLE
TaxRule action introduces a compatibility break

### ISSUE THREAD

**Issue by roadster31** [thelia/thelia#2059]
Before 2.3.0-alpha1, TaxRuleEvent::getCountryList() is expected to return an array of countries.

From 2.3.0-alpha1, TaxRuleEvent::getCountryList() is expected to return an array of arrays of countries and states IDs, possibly JSON encoded.

Modules such as ImportT1 which uses the TaxRuleEvent are now broken.

**Comment by gillesbourgeat** [comment]
Resolved by #2060
Thanks !
