### ISSUE TITLE
why thelia not use the twig?

### ISSUE THREAD

**Issue by benyang2015** [thelia/thelia#2070]

**Comment by roadster31** [comment]
https://github.com/thelia-modules/TheliaTwig

However, issues are not the place to discuss such items. Please use the [Thelia forum](http://thelia.net/forum) for this purpose.

**Comment by gillesbourgeat** [comment]
Hello,
Here is a response.
http://raynaud.io/2015/03/30/why-we-choose-smarty-in-thelia.html
We will try to integrate Twig in version 2.4 of Thelia.
