### ISSUE TITLE
Error on update to 2.3.0-beta1

### ISSUE THREAD

**Issue by lopes-vincent** [thelia/thelia#2088]
After an update to  2.3.0-beta1 I got error on any page with this error
`SQLSTATE[42000]: Syntax error or access violation: 1227 Access denied; you need (at least one of) the SUPER privilege(s) for this operation`

After some search I have found and fix the problem, he come from this modification #2012 who have issue with this server configuration :
- Server : MariaDB
- Version : 10.0.15

To fix temporarily I just remove the code added by this commit.

**Comment by roadster31** [comment]
I'm reproducing the problem with MariaDB.

**Comment by gillesbourgeat** [comment]
@lopes-vincent Can you test this fix ? #2091

**Comment by lopes-vincent** [comment]
It works, Thanks!

**Comment by roadster31** [comment]
:metal:

**Comment by gillesbourgeat** [comment]
@lopes-vincent Thanks !
