### ISSUE TITLE
Numérotation des Factures

### ISSUE THREAD

**Issue by netmedia84** [thelia/thelia#2111]
Bonjour, les factures sont générées à chaque commande même celles qui ne sont pas payées et c'est le numéro de commande qui est utilisé. Dans le cas ou le vendeur utilise ses factures pour sa compta ce n'est pas correct car les numéros de factures payées doivent obligatoirement se suivre. 

De plus lorsque seul le module de paiement Paybox est installé et actif, les factures non payées et annulée affichent "Paiement en carte bancaire Paybox". 

Je vois le module "Manage invoice ref" qui semble régler ce problème (je ne l'ai pas encore essayé car ma boutique est en production), ce module ne semble pas avoir évoluer depuis août 2014  il faudrait peut être intégrer cette fonction. 

C'est la première fois que j'interviens ici et mon premier THELIA 2 installé, donc un petit bravo à tous les développeurs pour ce superbe outil avec une ergonomie au top et merci de me lire.

**Comment by gillesbourgeat** [comment]
Bonjour, et merci à vous d'utiliser Thelia et nous faire confiance.

Vous pouvez tester le module https://github.com/thelia-modules/InvoiceRef qui génère bien un numéro de facture auto incrémenté quant la commande passe en payée.
Ce module n'a pas évolué depuis 2014 car son fonctionnement reste simple. Il écoute un événement et ajoute le numéros de facture..

Il existe aussi le forum Thelia pour échanger est poser vos questions http://thelia.net/forum/

Cordialement,

**Comment by netmedia84** [comment]
Merci Gilles de votre réactivité, me voilà rassuré.
Bonne journée
