### ISSUE TITLE
Crash modules

### ISSUE THREAD

**Issue by simplon-benjaminb** [thelia/thelia#2113]
Hi everybody!
Je sais pas parler anglais....bref...
Alors, lorsque vous installez la version 2.2.2 deThelia. Dans la partie admin/modules , lorsque on désactive tout les modules, Thelia plante et affiche une erreur "InvalidArgumentException in ContainerBuilder.php line 798: The service definition "thelia.parser" does not exist."
Voilà.
Merci.

**Comment by gillesbourgeat** [comment]
Bonjour,
Vous avez désactivé le module TheliaSmarty qui est utilisé pour rendre les tempaltes.
TheliaSmarty est un module essentiel à Thelia.
Pour régler votre problème, vous devez le réactiver depuis la base de données (Table module)
Il existe aussi le forum (Français) ou vous trouverez de l'aide http://thelia.net/forum/
Cordialement,

**Comment by simplon-benjaminb** [comment]
Merci ouip je vennais de refaire la manip en le reinstallant et en désactivant juste TheliaSmarty et ouip effectivement ...faut pas ^^
Merci 
Cordialement

**Comment by gillesbourgeat** [comment]
Du coup je ferme cette issue. Si vous avez besoin de plus d'aide, je vous invite à nous retrouver sur le forum.
