### ISSUE TITLE
SET @@GLOBAL.sql_mode='NO_ENGINE_SUBSTITUTION' is not working in all environments

### ISSUE THREAD

**Issue by roadster31** [thelia/thelia#2136]
If the DB user has no SUPER privileges (e.g. OVH SQL privé), `SET @@GLOBAL.sql_mode='NO_ENGINE_SUBSTITUTION'` fails.

We have to make some tests to check if `SET @@SESSION.sql_mode='NO_ENGINE_SUBSTITUTION'` is enough to support mySQL 5.6+

**Comment by Mandrilux** [comment]
Great
