### ISSUE TITLE
Cannot login in Thelia backend

### ISSUE THREAD

**Issue by SamueleColombo** [thelia/thelia#2192]
Hi,
I've a trouble with Thelia 2.3.1 and 2.3.2 because they don't allow me to login in the backend. 
The error is:

> Please check your input: Missing or invalid data: The CSRF token is invalid. Please try to resubmit the form.

I tried to change the version, to install another one or refresh the cache but those methods didn't work.

**Comment by matudelatower** [comment]
i have the same problem in 2.2.4 too

**Comment by roadster31** [comment]
Hello,

Issues are not the place to get support. Please use the [Thelia support forum](http://thelia.net/forum) for this purpose.

**Comment by roadster31** [comment]
Please check the cookie your web server is sending. If it uses the HttpOnly and Secure flags, be sure to use an https connexion, otherwise the PHP session cookie is not stored by the browser.
See this article for more details on this subject : https://geekflare.com/httponly-secure-cookie-apache/
