### ISSUE TITLE
Notice: Undefined property: Thelia\Core\EventListener\RequestListener::$eventDispatcher

### ISSUE THREAD

**Issue by matudelatower** [thelia/thelia#2193]
im ussing 2.2.3

when i try to change currency:

<img width="1280" alt="captura de pantalla 2016-06-18 a las 12 31 09 p m" src="https://cloud.githubusercontent.com/assets/5694115/16171860/ccd1595e-3550-11e6-9bc1-7ba2d35d3191.png">

**Comment by roadster31** [comment]
Hello,

Issues are not the place to get support. Please use the [Thelia support forum](https://thelia.net/forum) for this purpose.

**Comment by gillesbourgeat** [comment]
Hello,
You can apply https://github.com/thelia/thelia/pull/2194 for resolve your problem.
This bug would be fixed in to version 2.2.5
Best Regards,
