### ISSUE TITLE
Pays dupliqués dans le panier (estimation des frais de port) 

### ISSUE THREAD

**Issue by MageGaHell** [thelia/thelia#2216]
Installation simple d'un Thelia 2.3.2  : téléchargement du zip sur le site, déploiement des fichiers par FTP et installation par le wizard, sans rien de particulier.

La liste des pays est dupliquée dans le panier, dans la zone d'estimation des frais de port :
Screenshot du problème (le module 72h Colissimo est actif, mais le problème est le même sans)  :
![thelia001](https://cloud.githubusercontent.com/assets/11536796/16805762/02aa8788-4912-11e6-9658-5058c41a5a6e.jpg)

Un problème similaire avait été remonté sur une ancienne version, sur le forum : http://thelia.net/forum/viewtopic.php?id=11760

J'ai donc tenté de modifier le paramètre "Si une traduction est manquante ou incomplète par "Utiliser strictement la langue demandée", histoire de voir.
Cela empire le problème : 
![thelia002](https://cloud.githubusercontent.com/assets/11536796/16805998/fc26bf48-4912-11e6-9efb-2ac50f20006b.jpg)

**Comment by RAUPETIT** [comment]
Salut,

Le problème via du paramètre "with_area" de la loop country. Si tu le retire tu n'auras plus de doublons.

**Comment by MageGaHell** [comment]
Merci !
En effet, en remplaçant
`                                        {loop type="country" name="countryLoop" with_area="true"}
                                            <option value="{$ID}" {if $ID == $country_id }selected="selected" {/if}>{$TITLE}</option>
                                        {/loop}`
par : 
`                                        {loop type="country" name="countryLoop"}
                                            <option value="{$ID}" {if $ID == $country_id }selected="selected" {/if}>{$TITLE}</option>
                                        {/loop}`

Je n'ai plus de duplication de pays.
Néanmoins, ne vaudrait-il pas mieux de rendre ce paramètre option/configurable (vu qu'il est à "true" dans le template de base et donc provoque la duplication si on ne fait aucune modification ?).

NB : un with_area = "false" vide la liste des pays.

**Comment by RAUPETIT** [comment]
Au fait ce paramètre permet de lister les pays qui ont une zone de livraison. 99% des pays inscrit dans Thélia possèdent au moins deux zones de livraisons (ex : La France Métropolitaine est comprise dans les zones de livraison "Europe" et "France") d'ou les doublons.

Si tu passes ce paramètre à false, la loop va te sortir tous les pays qui ne sont pas assigné à une ou plusieurs zones de livraison et vu que dans Thélia aucun pays n'a pas de zone assigné, ça ne te renvoi aucun résultat.

En tout cas ça reste un bug que je vais tenter de corriger.

**Comment by RAUPETIT** [comment]
J'ai proposé une PR https://github.com/thelia/thelia/pull/2222
