### ISSUE TITLE
Bad parsing of web version in db update script

### ISSUE THREAD

**Issue by sb-relaxt-at** [thelia/thelia#2226]
When retrieving the latest version by querying http://thelia.net/version.php in [Update#getWebVersion](https://github.com/thelia/thelia/blob/master/core/lib/Thelia/Install/Update.php#L590), there is a trailing line break in the result. Therefore the update script believes, that the installed version is not the current stable release. There should be some sanitizing of the retrieved version information, at least the following is required in Update#getWebVersion: 

`$res = trim($res)`

**Comment by Asenar** [comment]
I didn't see the line break when downloading version.php but your fix may avoid problem, thanks you :)

**Comment by Asenar** [comment]
I didn't see the line break when downloading version.php but your fix may avoid problem, thanks you :)
