### ISSUE TITLE
Trouble with the pêrsistence of the currency in the front

### ISSUE THREAD

**Issue by yunai39** [thelia/thelia#2270]
Good morning,

I have noticed something troubling in the front of the demo. When an user is selecting the currency, they want to use, it is not persisted in the session.

The problem come from Thelia\Core\EventListener\RequestListener::checkCurrency.
if the request does not have the parameter currency then you override the currency in the session whever there is actually a currency in the session or not.

`    public function checkCurrency(GetResponseEvent $event)
    {
        /*\* @var Request $request */
        $request = $event->getRequest();

```
    if ($request->query->has("currency")) {
        if (null !== $find = CurrencyQuery::create()
                ->filterById($request->getSession()->getCurrency(true)->getId(), Criteria::NOT_EQUAL)
                ->filterByCode($request->query->get("currency"))
                ->findOne()
        ) {
            $request->getSession()->setCurrency($find);
            $this->eventDispatcher->dispatch(TheliaEvents::CHANGE_DEFAULT_CURRENCY, new CurrencyChangeEvent($find, $request));
        }
    } else {
        $request->getSession()->setCurrency(Currency::getDefaultCurrency());
    }
}`
```

Instead I override you code with this and it seems to work like a charm
`
    /**
     \* @param GetResponseEvent $event
     _/
    public function checkCurrency(GetResponseEvent $event)
    {
        /_\* @var Request $request */
        $request = $event->getRequest();
        $session = $event->getRequest()->getSession();

```
    if ($request->query->has("currency")) {
        if (null !== $find = CurrencyQuery::create()
                ->filterById($request->getSession()->getCurrency(true)->getId(), Criteria::NOT_EQUAL)
                ->filterByCode($request->query->get("currency"))
                ->findOne()
        ) {
            $request->getSession()->setCurrency($find);
            $this->eventDispatcher->dispatch(
                TheliaEvents::CHANGE_DEFAULT_CURRENCY,
                new CurrencyChangeEvent($find, $request)
            );
        }
    } else {
        // Si la session a déjà un currency on garde la currency actuel
        if (!$session->has('thelia.current.currency') ||
            $request->get('thelia.current.currency') instanceof Currency
        ) {
            $request->getSession()->setCurrency(Currency::getDefaultCurrency());
        }
    }
}
```

`

**Comment by edvincandon** [comment]
@yunai39 Thanks! I was about to open an issue regarding this matter! 👍 👍 👍
