### ISSUE TITLE
THELIA 2 ProductSearch + IndexEngine

### ISSUE THREAD

**Issue by bbrangeo** [thelia/thelia#2298]
Hi,

After click "Execute task" in backOffice 
Erreur
MESSAGE:  The options "constraints", "label", "label_attr", "required" do not exist. Defined options are: "choices

Thanks

**Comment by roadster31** [comment]
I can't find "Execute Task" anywhere in the back-office. Maybe you're talking about a module ?

**Comment by bbrangeo** [comment]
Bonjour,

Merci de m'avoir répondu.

Pour configuré IndexEngine (couplé avec elasticsearch) j'ai un bouton "Execute Task".
Si j'appuie, j'ai le message d'erreur 

MESSAGE: The options "constraints", "label", "label_attr", "required" do not exist. Defined options are: "choices

Tu as une idée.

D'autre part avec la dernière version de thelia, le module CriteriaSearch ne fonctionne pas.

J'aimerais avoir un slider (filter) pour les prix ?

Merci

**Comment by roadster31** [comment]
Ces issues sont relatives aux modules [IndexEngine](https://github.com/thelia-modules/IndexEngine) et [CriteriaSearch](https://github.com/thelia-modules/CriteriaSearch), et pas au core de Thelia.

Merci de les poster dans les issues des modules concernés, afin que leurs mainteneurs puissent être notifiés.
