### ISSUE TITLE
Check out as guest

### ISSUE THREAD

**Issue by madc** [thelia/thelia#2317]
Thelia v3.2.2

For small shops, which is the main target group for Thelia i'd assume, having the possibility to checkout as guest is extremely important. Are there plans on implementing this feature?

If not, we could use this issue to map out the concept and maybe someone will propose a PR.

**Comment by roadster31** [comment]
I have a module for this (used for example on http://www.franciskurkdjian.com), but it is not yet packaged (lack of budget :) ), thus not publicly available.

**Comment by madc** [comment]
First, thank you for the quick reply! And yes, of course, i meant v2.3.3.

I totally understand, that you want to keep the core small, even if I think, this should be a core feature. Would you be willing to provide the module you wrote? I would not expect any kind of support for it, but it may help me and other people to understand archive this feature.

**Comment by roadster31** [comment]
I'll put it on [my github](https://github.com/roadster31), with a WIP flag. Contributors are welcome.

**Comment by madc** [comment]
Any idea, when you will be able to publish the code? Would you link it here then?

**Comment by roadster31** [comment]
Have a look here: https://github.com/roadster31/ExpressCheckout
