### ISSUE TITLE
Order Action orderBeforePayment: duplicate ligne

### ISSUE THREAD

**Issue by yunai39** [thelia/thelia#2318]
Good morning,

In Thelia\Action\Order, in function orderBeforePayment there is twice the same ligne.

        /**
          * @param OrderEvent $event
          * @param $eventName
          * @param EventDispatcherInterface $dispatcher
          */
         public function orderBeforePayment(OrderEvent $event, $eventName, EventDispatcherInterface $dispatcher)
         {
             $dispatcher ->dispatch(TheliaEvents::ORDER_SEND_CONFIRMATION_EMAIL, clone $event);
     
             $dispatcher->dispatch(TheliaEvents::ORDER_SEND_NOTIFICATION_EMAIL, clone $event);
         }

**Comment by InformatiqueProg** [comment]
Looks more precisely
TheliaEvents::ORDER_SEND_CONFIRMATION_EMAIL (email for customer)
TheliaEvents::ORDER_SEND_NOTIFICATION_EMAIL (email for administrator)
