### ISSUE TITLE
Devise accessible en front même si elle n'est pas activée

### ISSUE THREAD

**Issue by yunai39** [thelia/thelia#2329]
Bonjour,

On vient de réaliser que la devise en front peut être accessible même si cette dernière n'est pas visible
Exemple
http://demo.thelia.net/?currency=CHF

**Comment by roadster31** [comment]
Bonjour,

C'est vrai. Il faut désactiver (et pas seulement masquer)  les devises que vous ne voulez pas rendre accessibles à vos clients.

**Comment by yunai39** [comment]
Les désactiver, c'est a dire les supprimer de la bdd ?

Le 21 décembre 2016 à 18:10, Franck Allimant <notifications@github.com> a
écrit :

**Comment by roadster31** [comment]
Ha pardon, je confonds avec les langues. La solution est de supprimer les devises dont tu n'as pas besoin.

**Comment by gillesbourgeat** [comment]
Bonjour,
A partir de Thelia 2.3.0 il est possible de masquer les devise depuis le backoffice.
Si les devises désactivées restent affichées en front, il manque surement un paramètre dans la loop
La doc va être mise à jour
http://doc.thelia.net/en/documentation/loop/currency.html

**Comment by yunai39** [comment]
Super !! Merci
