### ISSUE TITLE
allow usage of DKIM to send mail properly with SwiftMail

### ISSUE THREAD

**Issue by Asenar** [thelia/thelia#2336]
Hi,
a great feature would be to allow to sign mail with DKIM.

SwiftMailer library allow to send mail with DKIM but it's not possible with the core files of Thelia.

I quickly patched `core/lib/Thelia/Mailer/MailerFactory.php` (See the .diff file in a gist, below) but it would be better to make it possible with configuration only.

https://gist.github.com/Asenar/35074dac4b87f70b44d6908b2b28f1d2

**Comment by vz777** [comment]
Hi,
like @Asenar 
I think it would be great if it's possible in the configuration.

what about the development of this function ?

Thx
