### ISSUE TITLE
[BackOffice] Category page : Wrong product numbers  

### ISSUE THREAD

**Issue by stephaniepinet** [thelia/thelia#2350]
When you change a product's default category, the product keeps its order number, creating problems since the merchant can have 5 number 1, 4 number 2.... 
Is it possible de change automatically the product number by the last number + 1 ?

For example, I change the category of the product A to category AA. The category AA has 15 products. The product A, once in the category AA, should have the number 16.

**Comment by mbruchetpro** [comment]
With the last version of Thelia, your request works. It means that a product which change of category, it adapt itself. So with the last release of Thelia, your issue has been corrected.
