### ISSUE TITLE
LANGUAGE

### ISSUE THREAD

**Issue by markerbrain** [thelia/thelia#2353]
to developer of Thelia, i hope an Indonesia Language can be use soon on Thelia :)
I really like Thelia, but i can't install Indonesian Language
or, if someone can help me. please ..
Thank's

**Comment by acobster** [comment]
Hey there, please see [How to contribute new or update Thelia translations](http://doc.thelia.net/en/documentation/contribute.html#how-to-contribute-new-or-update-thelia-translations) for instructions on how to start translating into a new language. Thanks!
