### ISSUE TITLE
User info not updated in front if user is connected

### ISSUE THREAD

**Issue by TomPradat** [thelia/thelia#2358]
If an admin changes user information when the user is connected, the information are not updated in front because the customer is fetch from the security context which still have the previous information.

**Comment by roadster31** [comment]
This information is stored in the user session, which is not updated at each request.

Maybe we should perform this update at each request ?

**Comment by TomPradat** [comment]
No it's too much resourceful for our need, let's just change how the customer controller gets the user info for the route account/update, i'm making a PR
