### ISSUE TITLE
Add custom text when adding a product to a cart

### ISSUE THREAD

**Issue by arnaudsylvestre** [thelia/thelia#2360]
Hello,

I think it would be great to add a simple text input in a product in order to have a custom message related to the product.

For example, if i sell a T-Shirt with a custom text on it.

Best regards

**Comment by TomPradat** [comment]
Hi, i think this kind of specific development shouldn't be in thelia but in a thelia module.

**Comment by arnaudsylvestre** [comment]
I would like to implement it on a module.

Do you have any advice in order to implement it correctly ?
Can i reuse a hook or must i create a new one ?

Thanks in advance for your answer

**Comment by roadster31** [comment]
Issues are not the better lace for such requests. Please use the [Thelia support forum](https://forum.thelia.net) to get help.
