### ISSUE TITLE
Wrong order list when exporting complete order list

### ISSUE THREAD

**Issue by ngweb37** [thelia/thelia#2367]
Thelia 2.2.6 makes a bad csv file export when exporting the complete list of order in a range of dates.

These fields:
postage
total_including_taxes
total_with_discount
total_discount_and_postage
aren't be filled with the right value

**Comment by mbruchetpro** [comment]
Hello, 

Do you still get this type of export errors ? 
If yes, can you explain how do you get those ? 

Because with the latest version with Thelia this not still an issue.
