### ISSUE TITLE
changer l'ordre du carousel d'image de la page d'accueil

### ISSUE THREAD

**Issue by lucavlw** [thelia/thelia#2370]
Pour l'instant il n'est pas possible de changer l'ordre des slides dans le carousel de la page d'accueil. c'est très laborieux de devoir supprimer et intégrer dans l'ordre les images.
je pense qu'il serait bénéfique de pouvoir le faire.

**Comment by zorn-v** [comment]
You can change 
`<input type="hidden" name="{$name}" value={$POSITION}>`
to
`<input type="text" name="{$name}" value={$POSITION}>`
in
`local/modules/Carousel/templates/backOffice/default/module_configuration.html`
and you get inputs for position (with ugly style, but better than nothing)

Don't trust {* Not yet implemented *} - it works fine

**Comment by lucavlw** [comment]
Great ! Thanks Zorn ! Thelia should include this (with a little style :) ) in next update !

**Comment by zorn-v** [comment]
Just make a pull request 😉  with some styles

**Comment by zorn-v** [comment]
But its no so fast...
https://github.com/thelia/thelia/pull/2361
I still modify that damned carousel module to work on machine without images in dev DB.
