### ISSUE TITLE
Error on Command export list/use archiver

### ISSUE THREAD

**Issue by InformatiqueProg** [thelia/thelia#2388]
php Thelia export --list-archiver
Throw Exception if one archiver extension is not load
![capture](https://cloud.githubusercontent.com/assets/7933327/26250585/cc78b3c8-3caa-11e7-9185-3cbbf535d66c.JPG)

**Comment by InformatiqueProg** [comment]
This bug was added by this PR #2030 (i think)

**Comment by roadster31** [comment]
Closed by #2389
