### ISSUE TITLE
Thelia perspective

### ISSUE THREAD

**Issue by zorn-v** [thelia/thelia#2393]
It have great architecture and codebase. But seems promotion goes slow (2.4.0-alpha1 dated 19 Sep 2016).
Some of improvements for modules (https://github.com/thelia/thelia/pull/2374 for example) does not put in module repo for installing thru composer via `dev-master` version.
Maybe need help for organization ?

**Comment by roadster31** [comment]
The available resources on the project have decreased since the beginning of the year. Any help is very welcome.

**Comment by zorn-v** [comment]
What about just bump versions to packagist ?
What about `thelia-project` ?
How should user to do ?
Lets take https://github.com/thelia/thelia/issues/2399
He MUST git clone etc.
In ideal he just change version in `composer.json` and `composer update`

Some of bugs is critical sometimes. Such https://github.com/thelia/thelia/pull/2376 wich I implemented in plugin named `TheliaFixes` coz I can just update thru composer.

**Comment by roadster31** [comment]
A bot will update core modules and thelia-project. 

I'llcheck with open studio guys the release process in june. 

Please be patient :-)
