### ISSUE TITLE
update Attributes and Features

### ISSUE THREAD

**Issue by ginodm** [thelia/thelia#2399]
Hi all,
I'm new to Thelia. I have installed the latest version 2.3.3 but I encountered a bit problem.

I creates the **product feature**  to insert the constant in tax roules.

I add the **Taxes and Tax rules to create a new Taxes with Type Constant amount found in one of the product's feature** and select my feature.

When I insert the **feature** value in Product the value is showed correctly but into db in table _feature_product_ in column _free_text_value_ I see the value 1.

I tried to find the events that manage the inset this data into db but I did not successed.

I hope it is clear.

Please somebody can help me to solve this problem.

Thank you

**Comment by zorn-v** [comment]
That tax rule type is broken. This PR https://github.com/thelia/thelia/pull/2392 will fix it when finished. 
But you need to install 2.4.0-alpha2 (when it bumped) to use it

**Comment by zorn-v** [comment]
Better fix https://github.com/thelia/thelia/pull/2392/commits/aed4ddadd81f459e9ce3c5b6b5ea50d2f188836a
You can provide different amounts for different locales with it
