### ISSUE TITLE
Impossible to create new customer

### ISSUE THREAD

**Issue by arnaudsylvestre** [thelia/thelia#2401]
Hi,

it seems that it is not possible to create a new customer in the current master branch (it worked on 2.3.3).
I got the following error

> Unable to execute INSERT statement [INSERT INTO 'address' ('ID', 'LABEL', 'CUSTOMER_ID', 'TITLE_ID', 'FIRSTNAME', 'LASTNAME', 'ADDRESS1', 'ZIPCODE', 'CITY', 'COUNTRY_ID', 'IS_DEFAULT', 'CREATED_AT', 'UPDATED_AT') VALUES (:p0, :p1, :p2, :p3, :p4, :p5, :p6, :p7, :p8, :p9, :p10, :p11, :p12)]

It seems that it is related to the fact that there is no address2 and address3 fields and they are mandatory in database...
I tried to fill the values of those two fields in debug mode and it worked...

**Comment by zorn-v** [comment]
>it worked on 2.3.3

https://github.com/thelia/thelia/blob/2.3.3/setup/thelia.sql#L516
I think it was not changed since the beginning of time. 
Just check your mysql config. Take a look for `strict_trans_tables` mode.

**Comment by arnaudsylvestre** [comment]
> I think it was not changed since the beginning of time.

Indeed, I already checked this before

> Just check your mysql config. Take a look for strict_trans_tables mode.

I didn't change my mysql config between the two versions...
I think I will try to go back to version 2.3.3 in debug mode to understand what happened...

**Comment by roadster31** [comment]
@arnaudsylvestre , did you get additional information about this issue ?
