### ISSUE TITLE
A brand off-line is "on-line" when you edit it

### ISSUE THREAD

**Issue by InformatiqueProg** [thelia/thelia#2439]
On THELIA 2.3.3
![list](https://user-images.githubusercontent.com/7933327/31536153-e80c89b8-affd-11e7-8498-8edf8f088d18.JPG)
![edit](https://user-images.githubusercontent.com/7933327/31536158-eb8bdde6-affd-11e7-8302-759f40569cb0.JPG)

**Comment by roadster31** [comment]
Nice catch.

**Comment by roadster31** [comment]
Closed by #2440
