### ISSUE TITLE
Mise a jour par l'application 

### ISSUE THREAD

**Issue by gimlyGVD** [thelia/thelia#2443]
Pourrait-on avoir une possibilité de mise à jour directement dans l'administration de Thalia, par téléchargement du zip ou même directement Thalia qui le téléchargerait

**Comment by gillesbourgeat** [comment]
Bonjour,
Cela est à l’étude.
Il est extrêmement complexe de mettre en place une mise à jour automatique sur une application qui a des dépendances, car beaucoup de code n'appartient pas à l'application.
Il faut aussi que la base de donnée soit bien patchée pendant la mise à jour.
La partie ci-dessus est en test dans une pull request https://github.com/thelia/thelia/pull/2635

Cordialement,
