### ISSUE TITLE
Version 2.3.4 not installable

### ISSUE THREAD

**Issue by zorn-v** [thelia/thelia#2446]
First - there is no thelia-project for 2.3.4 
If you update to it you MUST create favicon.png and logo.png
And you can not do it thru admin panel coz it will throw exception too.

This all smells like a shit.

**Comment by roadster31** [comment]
> This all smells like a shit.

Such comments are not welcome here.

**Comment by zorn-v** [comment]
Sorry for straightness.
But I feel ssomething like "there was perfect framework for shop, but now %$!@#%$"

**Comment by zorn-v** [comment]
I know that you are the one. But on thats things (like you cannot just run it without some doings) I'm disappointed

**Comment by zorn-v** [comment]
BTW. thelia/thelia-project is out of date.
Can you give me rights for "fix" it ?

**Comment by roadster31** [comment]
The 2.3.4 release of thelia-project has just been created.

Jingle bells.

**Comment by zorn-v** [comment]
I know, and because of it I'm asking.
Got 2.3.4 you shoud install, change version in composer, MANUALLY (coz admin panel does not work for this) upload favicon.png and logo.png (paths you should get from exception messages). 
Wow You installed 2.3.4

**Comment by roadster31** [comment]
Explaining your issue like this is fine. At least better than just ranting and talking of 'shit'.

Whatever. Could you please open a new issue related to this specific problem ?
