### ISSUE TITLE
Can not login as back office in demo page

### ISSUE THREAD

**Issue by ikandars** [thelia/thelia#2449]
Hi,

I can not login as back office in demo page http://demo.thelia.net/admin/login

The error said: Please check your input: Missing or invalid data: The CSRF token is invalid. Please try to resubmit the form.

<img width="1154" alt="screen shot 2017-11-06 at 09 00 50" src="https://user-images.githubusercontent.com/289726/32422157-13f2a5c2-c2d1-11e7-85ef-be28b19a8768.png">

**Comment by roadster31** [comment]
The problem is solved. Thanks for reporting it.
