### ISSUE TITLE
bug php 7.2.1

### ISSUE THREAD

**Issue by gimlyGVD** [thelia/thelia#2473]
mamp ma proposé un Maj que j'ai faite et sans me le demander il ma passé en php 7.2.1.
et page blanche dans les produit de back office
plus de problème en 7.1.12

1/1
FatalErrorException in ProductModificationForm.php line 22:
Compile Error: Declaration of Thelia\Form\ProductModificationForm::buildForm() must be compatible with Thelia\Form\ProductCreationForm::buildForm($change_mode = false)

**Comment by roadster31** [comment]
Thelia ne peut pas être utilisé avec PHP 7.2, c'est PHP 7.1 maximum.
