### ISSUE TITLE
Module model files are not always written in the <module>/Model directory

### ISSUE THREAD

**Issue by roadster31** [thelia/thelia#2491]
When a module model is generated for the first time on the command line, the model files are written in <module>/Model directory. This is fine.

However, when the schema.xml is changed and the module model re-generated  on the command line, the model files are not written in the <module>/Model directory.

**Comment by roadster31** [comment]
Any news about this issue ?

**Comment by bcbrr** [comment]
I can't reproduce the issue: I added a table to the `schema.xml` of a module, and the corresponding model and query classes are generated in that module `/Model` directory.

Only changes that add or remove tables (so adding or removing a table, or adding or removing a behavior that adds a table) should change something, or am I wrong ?

Or is it about also generating the `Base/` Propel classes in the module `Model/` directory, for compatibility with previous Thelia versions ?

**Comment by bcbrr** [comment]
Sorry I still can't reproduce the issue, that works for me.

I tried activating/deactivating the module, works in both cases.
