### ISSUE TITLE
New Install

### ISSUE THREAD

**Issue by xgeekgirlx** [thelia/thelia#2514]
I clicked into the Store Configuration to edit Store COnfiguration, and received this error:
Oops! An Error Occurred
An unexpected error occurred
The page you've requested has a problem. Please contact the module developer if you were using one, or feel free to give the Thelia team a feedback on github: here.

The following error message has been found: Failed to create symbolic link for favicon.png in store image cache directory

**Comment by roadster31** [comment]
Try to set the configuration variable original_document_delivery_mode to "copy" instead of "symlink"

**Comment by xgeekgirlx** [comment]
well thanks, I am assuming you mean in the code of the config file? Or do you mean a setting once I get into the configuration?

I did get the site to load by FTPing the logo pic into the directory manually. However, I cannot figure out the proper storage area for the product and category pics, or the nomenclature format they need, as the software will not upload any pics. it goes through the motions - upload and 'saves' it,, but does not actually save any pic in any category or product. It's a blank placeholder image on the back end, and shows nothing on the front end.

It also is not recognizing that I uploaded a product in a subcategory within the parent category. You can see that here. http://charitycases.org/store/web/?view=category&lang=en_US&category_id=1

I may try and figure this out, but with so many issues not working from step one, I am not sure the level of effort needed to get it to work 'correctly.'

**Comment by roadster31** [comment]
In the back office, click Configuration, then Configuration variables, and change the value of original_document_delivery_mode

**Comment by xgeekgirlx** [comment]
I feel like a newb here. I can't even figure out where I am supposed to login on the back end. None of the login fields are accepting my credentials; everything else is giving me 403 Forbidden errors.

Now that it has been overnight, obv my browser session has expired and redirected elsewhere and I cannot get back to where I was formerly. What might the normal/standard path to login to the admin be?

**Comment by roadster31** [comment]
http://whatever-is-your.tld/admin

**Comment by xgeekgirlx** [comment]
I'm sorry there is no admin folder. No need to reply... this has far too many issues for me to recommend it.

**Comment by roadster31** [comment]
No admin folder, for sure, but a /admin route: http://charitycases.org/store/web/index.php/admin

**Comment by morrischege1** [comment]
Hi i have been trying to update the shipping module and installed a shipping plug in but now when I tried to activate it I received the error above what shoul I do?

**Comment by roadster31** [comment]
Try to set the configuration variable original_document_delivery_mode to "copy" instead of "symlink"

**Comment by morrischege1** [comment]
this is what i see when i click on configuration how do i go about it 
![Thelia configuaration](https://user-images.githubusercontent.com/52851855/61197122-c84c4100-a6db-11e9-9bbc-0289062bbbdd.JPG)

**Comment by morrischege1** [comment]
I have finally found it and it was already on copy

**Comment by morrischege1** [comment]
this is the actual error that I get 
![Website error](https://user-images.githubusercontent.com/52851855/61198704-d1d9a700-a6e3-11e9-8824-76f0e94764cc.JPG)

**Comment by roadster31** [comment]
Is this a fresh install ? Do you have some modules already installed and activated ?

**Comment by morrischege1** [comment]
no its not a fresh install, yes there are already other modules installed and activated. though i have alredy managed to get the website back online.
My only problem now is how to set the shipping fee where by I want to set the shipping fee at 300ksh and free delivery for orders above 5000ksh.
I have installed a module by the name "FreeDelivery-master" it working for orders above 5000ksh but for the ones below 5000ksh its only charging 22.52ksh

**Comment by roadster31** [comment]
OK, your question is non longer related to this issue. Please go to the module repo and post the issue there.

**Comment by morrischege1** [comment]
Ok thank you so much for your quick response let me do so
