### ISSUE TITLE
No default currency is defined. Please define one.

### ISSUE THREAD

**Issue by tealborder** [thelia/thelia#2515]
After using composer create etc, I passed through the web install just fine. I began to add new products but realized they were in a foreign currency, maybe euros I dont know. I found the 'change currency' page and the european would not turn off. I enabled the dollar and then it all went wrong.

Visiting any page, I get:
> An unexpected error occurred
> The page you've requested has a problem. Please contact the module developer if you were using one, or feel free to give the Thelia team a feedback on github: here.
> 
> The following error message has been found: No default currency is defined. Please define one.

Where to change the value for this? Is it in the db or a config file?
Thanks! Can't wait to try Thelia some more.

**Comment by roadster31** [comment]
Did you set the Dollar as the default currency ?

**Comment by tealborder** [comment]
The aim was to set the Dollar as the default currency. For whatever reason, the UI wasn't having it. Should I scrap the entire thing and start over or where is this value set?

**Comment by roadster31** [comment]
The default currency is set in the "currency" table in the database.

**Comment by roadster31** [comment]
Any update about this issue ?
