### ISSUE TITLE
"Unable to execute INSERT statement" with Thelia 2.3.4

### ISSUE THREAD

**Issue by hdegorce** [thelia/thelia#2523]
Whether the application is a new installation or not, we can't INSERT when the database is on a MariaDB 10.2 version.
It worked with MariaDB 10.1.

We tried only with an insert of a new customer but it should be the same of other items.

**Comment by roadster31** [comment]
Thanks for reporting the problem. Could you please copy/paste here the error message you get ?

**Comment by hdegorce** [comment]
I don't have anything more it's in the admin interface.
In the Home of the admin I have "An error occurred while reading from JSON file" I don't know if it's linked.

**Comment by roadster31** [comment]
Could you please try in development mode (https://your.domain.tld/index_dev.php/admin 

You have to put your IP address in index_dev.php for this to work : 

```
// List of allowed IP
$trustedIp = array(
  '::1',
  '127.0.0.1',
  'your.ip.address.here',
);
```

**Comment by hdegorce** [comment]
Nothing change. I just checked logs and some information helped me. When we enter all information (so all additional street addresses) it worked. The error message was:
`32: ERROR [Propel.php:log()] {284} 2018-10-02 11:37:16: SQLSTATE[HY000]: General error: 1364 Field 'address2' doesn't have a default value`

I also have an errror when I tried to change the log configuration:
`15: ERROR [Propel.php:log()] {284} 2018-10-02 11:42:17: SQLSTATE[HY000]: General error: 1364 Field 'value' doesn't have a default value`

**Comment by roadster31** [comment]
Please have a look at https://ourcodeworld.com/articles/read/757/how-to-solve-mysql-exception-sqlstatehy000-general-error-1364-field-field-name-doesnt-have-a-default-value

Does the second solution (B. Server Side Solution) solves your problem ?

**Comment by hdegorce** [comment]
Thanks for your reply. Unfortunately, it's not possible as my account is on shared servers and sysadmins win't do this kind of modification.

**Comment by RomainMazB** [comment]
I guess this could be closed since it's solved by [the documentation's installation process](http://doc.thelia.net/en/documentation/installation/index.html#mysql-56):
> SET @@GLOBAL.sql_mode='NO_ENGINE_SUBSTITUTION', @@SESSION.sql_mode='NO_ENGINE_SUBSTITUTION'

I've faced the same here and this solved the issue.
