### ISSUE TITLE
recherche dans "ADRESSE DE LIVRAISON"

### ISSUE THREAD

**Issue by gimlyGVD** [thelia/thelia#2592]
bonjour, 

Pourrai t on avoir la recherche dans l'adresse de livraison, en plus de l'adresse de facturation 

j'ai un client qui a mis un "nom1" dans adresse de facturation et un "nom2" dans adresse de livraison

quand je recherche (en haut a gauche du back office) "nom1" pas de problème, mais si je mets "Nom2", il ne trouve pas

**Comment by gillesbourgeat** [comment]
Bonjour,

Votre demande d'amélioration a été réalisée par @lopes-vincent dans la pull request #2646
Cette amélioration sera donc disponible dans la 2.4

Cordialement,
