### ISSUE TITLE
erreur 404 avec une adresse avec un + a la fin

### ISSUE THREAD

**Issue by gimlyGVD** [thelia/thelia#2594]
une adresse avec un + a la fin génère un erreur 404
lasure-cecil-lx-545+.html ----> erreur 404
lasure-cecil-lx-545.html -----> pas de problème

**Comment by gimlyGVD** [comment]
ok j'avais même essayer le %2b sans succès

**Comment by roadster31** [comment]
On pourrait sans doute contrôler l'URL saisie pour echapper les caractères réservés

**Comment by gimlyGVD** [comment]
a voir si quelqu'un a le temps de le faire, finalement j'ai fini avec "plus"
