### ISSUE TITLE
Promo ne se desactive pas

### ISSUE THREAD

**Issue by thibs05** [thelia/thelia#2641]
Bonjour,

lors d'une création d'une promo (Gestion des promotions), lorsque l'on rentre une date de fin, celle ci ne se désactive pas à la date entrée.

Après cette date, les produits reste avec promo=1.

**Comment by gillesbourgeat** [comment]
Bonjour,

La gestion de l'activation/désactivation des promos passe par un cron

La commande Thelia pour le cron est
```bash
php Thelia sale:check-activation
```

**Comment by thibs05** [comment]
Ok merci, nous allons le rajouter dans notre fichier cron
