### ISSUE TITLE
ClassNotFoundException in ConfigQuery.php

### ISSUE THREAD

**Issue by katsuya06** [thelia/thelia#2656]
Bonjour,
J'utilise Thelia 2.4.0 et depuis hier après avoir crée un module ( que j'ai supprimé par la suite), j'ai l'erreur suivante qui s'affiche : 
```
ClassNotFoundException in ConfigQuery.php line 17: Attempted to load class "ConfigQuery" from namespace "Thelia\Model\Base".
Did you forget a "use" statement for another namespace?
```
Le fichier existe bien pourtant. J'ai vider les caches manuellement mais je n'arrive toujours pas à accéder à mon site.

Auriez vous des idées ?

Merci

**Comment by roadster31** [comment]
Supprimez complètement le contenu du dossier cache.

**Comment by gillesbourgeat** [comment]
Hello,
Tu utilises Thelia master ou Thelia project ?

**Comment by katsuya06** [comment]
J'utilise la version Master. 

Même en supprimant tout les fichiers du dossier cache j'ai la même erreur.

**Comment by katsuya06** [comment]
Bon j'ai régler le problème en réinstallant une version de Thelia puis j'ai remis les modules que j'avais créer. Merci
