### ISSUE TITLE
Improve translation process

### ISSUE THREAD

**Issue by lopes-vincent** [thelia/thelia#2682]
We need to improve the process for translation, a good way could be an export/import of ".po" files who override current translation with php arrays, and allow user to use translation tools like poEdit or other.

There is the process :

Export : 

- Get all current I18ns (key => value) for all langs and domain from classic I18ns or ‘’.po’’ if already exists
- Parse files (php, tpl, html, ...) to get not already defined translatable strings
- Export this keys values as ‘’.po’' files

Import :

- Make a backup of existing ''.po’’ 
- Save the new files

Translation : 

- If no ‘’.po’’ exist use classic I18ns 
- Else if ‘’.po’’ files exists use it (And disable translation admin tools with message that this is not available when using ‘’.po’' files)

**Comment by nicolasleon** [comment]
+1
