### ISSUE TITLE
Setting shipping fee on Thelia 2.3.2

### ISSUE THREAD

**Issue by morrischege1** [thelia/thelia#2686]
I am trying to set the shipping fee where by I want to set the shipping fee at 300ksh and free delivery for orders above 5000ksh.
I have installed a module by the name "FreeDelivery-master" it is working for orders above 5000ksh but for the ones below 5000ksh it's only charging 22.52ksh how can I make it charge 300ksh?

**Comment by nicolasleon** [comment]
Hi,
Your request is more like a configuration issue. Please post it in the Thelia forum [http://forum.thelia.net/](http://forum.thelia.net/)
