### ISSUE TITLE
getCurrentOrderTotalAmount -> no discount calculated

### ISSUE THREAD

**Issue by valentin3522** [thelia/thelia#2690]
getCurrentOrderTotalAmount(true,true,true) give the total price WITHOUT discount.

must use $order->getTotalAmount();

**Comment by roadster31** [comment]
Please have a look at the method description:
```
     * A convenient method to get the current order total, with or without tax, discount or postage.
     * This method operates on the order currently in the user's session, and should not be used to
     * get the total amount of an order already stored in the database. For such orders, use
     * Order::getTotalAmount() method.
```
When this method is called in the pay() method of a payment module, the coupons (and this the discount) has already been been removed from the user session.

However, this method is useful for delivery modules or any module needing the cart total before payement process is started.
