### ISSUE TITLE
Spanish and Italian translation are not completed

### ISSUE THREAD

**Issue by roadster31** [thelia/thelia#272]
Spanish and Italian translation are not completed yet.

**Comment by fluppi** [comment]
still remains something but I'll fix it soon.

**Comment by bibich** [comment]
great.
I closed this issue because now we can use https://crowdin.com/project/thelia to translate Thelia in any languages.
So when all translations are available in a new language it's included in Thelia.

**Comment by fluppi** [comment]
Great :-)
