### ISSUE TITLE
backOffice - use other template - I18n

### ISSUE THREAD

**Issue by zzuutt** [thelia/thelia#2778]
When using a template other than the default one, translations (folder I18n) are not taken into account.

**Comment by roadster31** [comment]
C'est à dire ? Il se passe quoi exactement ?

**Comment by zzuutt** [comment]
exemple la page de login cote back
je copie le dossier I18n et les fichiers login.html et simple-layout.tpl  dans mon nouveau template
je modifie dans le fr_FR.php
'Welcome to Thelia administration !' => 'test traduction!',

j'active le template dans la config
vide les caches
j'affiche la page login en FR
le texte n'a pas changé "Bienvenue sur l'administration de Thelia !"

**Comment by roadster31** [comment]
Normal. tant que tu ne changes pas `{default_translation_domain domain='bo.default'}` en ligne 14 de `admin-layout.tpl`, ce seront les traduction de `default` qui seront utilisées.

**Comment by zzuutt** [comment]
yep 
pff la mémoire qui flanche...  début d’Alzheimer...
je me doutais que j'oubliais quelque chose
