### ISSUE TITLE
problem with breadcrumb if product is multi-category

### ISSUE THREAD

**Issue by vz777** [thelia/thelia#2803]
In a product page,
there is a problem with breadcrumbs when a product is multi-category.
If it's default category  is online, only this default is displayed.

If its default category is not online, category in the breadcrumb isn't displayed.

I think there is two ways to consider solving the problem : 
- breadrcumb of the path taken by the client
- breadcrumb which displays all the possible paths like : Home / cat1 / product Home / cat2 /product

I would rather want the second solution

**Comment by lopes-vincent** [comment]
From an SEO point of view it is better that a product has a default category and that the breadcrumb is that of this category.
Afterwards if this does not work as needed, it is easy to modify the template to have the right breadcrumb.
