### ISSUE TITLE
Fix PHP 7.4 Warnings

### ISSUE THREAD

**Issue by Alberttyty** [thelia/thelia#2816]
Hi, Thelia 2.4 seems to be ok in PHP 7.4 but there are theses warnings :
1. An easy pick to begin : replace implode(array $array, string $separator) by implode(string $separator, array $array)
mod_fcgid: stderr: PHP Deprecated: implode(): Passing glue string after array is deprecated.
Swap the parameters in /core/vendor/thelia/propel/src/Propel/Runtime/ActiveQuery/Join.php on line 669
Remove parent:: from Propel Object Model without parent Object  

2. An other pick : Remove parent:: from Propel Object Model without parent Object
See /core/vendor/thelia/propel/src/Propel/Generator/Builder/Om/templates/baseObjectMethodHook.php
Example : replace
````
if (is_callable('parent::preSave')) {
    return parent::preSave($con);
}
````
by
````
<?php if (get_parent_class($eventClass)):?>
if (is_callable('parent::preSave')) {
    return parent::preSave($con);
}
<?php endif?>
````

**Comment by lopes-vincent** [comment]
Hi, thanks for this information.

But sorry we have not a lot of time to spent on 2.4 now, a 2.4.4 will be released soon but with minor change.   
We are currently working hard to make Thelia 2.5 with an update of all components to latest Symfony version (5.2) and a Php compatibility up to 8.
This major release will have some breaking change, we are trying to make it easy to update from 2.4, but it will surely not be "out of the box" update and will require some refactoring of your modules. 
So if you want 7.4 to Thelia 2.4, and you know what to do please make use a PR to our propel fork at the branch thelia-2.4 https://github.com/thelia/Propel2/tree/thelia-2.4
And if it works we will put it in 2.4.4 with pleasure.

**Comment by Alberttyty** [comment]
I did and thanks for this epic news. Do not hesitate for some helps.
