### ISSUE TITLE
Error while installing Thelia 2.5.0

### ISSUE THREAD

**Issue by prbt2016** [thelia/thelia#3025]
### Thelia version(s) affected

2.5.0

### Description

Hello @lopes-vincent ,

I was in the process of manual installation of Thelia 2.5.0 on Centos 7 with PHP 8.0.22, MYSQL 5.6, Apache 2.2 . 
I followed the following steps to install : 

- Downloaded Thelia 2.5.0 package from https://github.com/thelia/thelia-project/archive/refs/tags/2.5.0.zip 
- Unzipped the package
- Installed composer `curl -sS https://getcomposer.org/installer | php`
- Run command  `php composer.phar install`

After the dependencies got installed I visited : 

http://domain.com/thelia250/web

I get the following error i.e Thelia is not installed  : 

![image](https://user-images.githubusercontent.com/17871448/187182360-4e69e749-ed73-4e0a-aea7-4b546c931551.png)

Is there any way to get the install wizard running?. Has the installation process for Thelia 2.5.0 changed.

Also where can I find updated docs for installing Thelia 2.5.0. 

Seems that the documentation https://doc.thelia.net/en/documentation/installation/index.html is too old.

Please help.

### How to reproduce

- Download Thelia 2.5.0 package from https://github.com/thelia/thelia-project/archive/refs/tags/2.5.0.zip 
- Unzip the package
- Install composer `curl -sS https://getcomposer.org/installer | php`
- Run command  `php composer.phar install`

Visit http://domain.com/thelia250/web in the browser and error is thrown i.e : 

Thelia is not installed.

**Comment by prbt2016** [comment]
Update : 

Found the documentation at https://doc.thelia.net/docs/getting_started/Installation for Thelia 2.5.0 . 
I installed Thelia via Composer and CLI install as mentioned in the docs. 

However I get the following error while adding an user  or updating admin detailsi.e : 

Environment variable not found: "MAILER_DSN".


Here is the screenshot of the same : 


![image](https://user-images.githubusercontent.com/17871448/187434394-b0e6516d-9caf-48b8-b033-bc7055e726f1.png)


How to resolve this issue ? . Is it a known issue?. 

Kindly help .

Regards.

**Comment by lopes-vincent** [comment]
Hello,
Firstly, sorry for your first issue, I didn't see your message before.

Ok I see a little issue, I will do a patch for the next version but for now you can fix it by either configure your mailer in `.env` like explain here https://symfony.com/doc/6.0/mailer.html#using-built-in-transports or enable and configure the smtp by Thelia interface here `/admin/configuration/mailingSystem`.     
Or if you don't care of mail, just uncomment this line `MAILER_DSN=null://null`  in `.env`

**Comment by prbt2016** [comment]
Hello @lopes-vincent ,

Thanks for looking into the issue.  I checked by uncommenting `MAILER_DSN=null://null`  in  `.env` file and it works fine for now . 
Thanks for the turnaround.

Any ETA for the next release?

Regards.

**Comment by lopes-vincent** [comment]
Hello, fixed by PR #3037 for release 2.5.1 coming in 1 or 2 weeks

**Comment by prbt2016** [comment]
Hello ,

Thanks for the fix. 

Regards.

**Comment by prbt2016** [comment]
Hello @lopes-vincent ,

Had a small query. Is 2.5.0 a stable release to use for production? . 

On official website the latest version shown is 2.5.0-alpha2.

Is website not updated ?.

![image](https://user-images.githubusercontent.com/17871448/190133640-d1899dbe-4049-4fa8-a822-b2f5fc54d532.png)

Kindly let me know.
