### ISSUE TITLE
modern template does not work if current template is not defined in .env

### ISSUE THREAD

**Issue by roadster31** [thelia/thelia#3029]
### Thelia version(s) affected

2.5.0

### Description

The current front template must be defined in a .env file for the `modern` template to work properly, as the `ACTIVE_FRONT_TEMPLATE` variable is used in various configuration files.

Thus, defining the current front template in the Thelia back-office is not enough, as the default value of `ACTIVE_FRONT_TEMPLATE` remains `default`

![image](https://user-images.githubusercontent.com/2197734/187680607-bfa21b9a-341e-4b56-9531-640aa0cf1606.png)

.env.local :

```
... 
DEBUG_TRUSTED_IP=127.0.0.1
#ACTIVE_FRONT_TEMPLATE=modern
MAILER_DSN=smtp://localhost:25
#ACTIVE_ADMIN_TEMPLATE=modern-bo
```

Error when trying to load index page

![image](https://user-images.githubusercontent.com/2197734/187680140-9b3b7b50-9557-48ab-b865-65d371782a36.png)

### How to reproduce

Set the front template to 'modern' in the Thelia BO
Comment the `ACTIVE_FRONT_TEMPLATE=modern` line in various .env files

**Comment by lopes-vincent** [comment]
Fixed by #3039
