### ISSUE TITLE
FileManager design prevent any re-use nor extension

### ISSUE THREAD

**Issue by roadster31** [thelia/thelia#363]
The design of FileManager prevent any further extension by modules.As the possible image parents are hard coded (products / categories / contents / folders, and that's all).

This could be improved by implementing a base class, which is extended for each image or document possible parent. We have thus mores classes, but much more flexibility.

Also, permissions management in this controller uses reflection on the AdminResources class to read a constant value. The name of this constant is built using a parameter of the URL. 
This should be improved, as maintainability of such a solution is far from optimal

**Comment by lopes-vincent** [comment]
This is partially done by this module https://github.com/thelia-modules/TheliaLibrary
