### ISSUE TITLE
[WIP] Module activation enhancement

### ISSUE THREAD

**Issue by lunika** [thelia/thelia#392]
Many actions on module activation can be automated : 

* Sql insertion : many modules need to create tables, insert some data in database, etc. Propel can generate a sql file. It would be usefull to execute an indicated sql file when module is activated.
* image insertion : manipulating module's images is not simple. This task can be automated by indicated in module.xml file which imagescan be insert in database and copy in media directory.

| Action  | implemented ? |
| ------------- | ------------- |
| Sql insertion  | No  |
| image insertion  | No |

**Comment by lovenunu** [comment]
Image insertion is automated in #1060, and automated sql insert can be done using https://github.com/thelia-modules/TheliaStudio , does it belong to the needs of this issue ?

**Comment by lunika** [comment]
close it <3

**Comment by lovenunu** [comment]
oh, my dear <3
