### ISSUE TITLE
Wrong permissions check for TinyMCE file manager

### ISSUE THREAD

**Issue by roadster31** [thelia/thelia#411]
In the tinymce/plugins/filemanager/config/config.php file , the following permissions are checked for UPDATE and CREATE:

       \Thelia\Core\Security\Resource\AdminResources::PRODUCT,
       \Thelia\Core\Security\Resource\AdminResources::CATEGORY,
       \Thelia\Core\Security\Resource\AdminResources::FOLDER,
       \Thelia\Core\Security\Resource\AdminResources::CONTENT,

This is wrong, as some back-office user may have permission only for CONTENT, and not for other items.

Thus a back-office user that do not have all these permissions sees a blank dialog, without any error message nor clue about what happens.

**Comment by lovenunu** [comment]
Waou, fixed by #485 . I'm an issue gravedigger tonight :D
