### ISSUE TITLE
Image loop cannot return an image from its ID

### ISSUE THREAD

**Issue by roadster31** [thelia/thelia#467]
It is not possible to get a specific image given its ID and the related object. For example, if ones want the content image with ID 12 :

`{loop type="image" name="sa-beugue" source="content" id="12"}
...
{/loop}`

The error is :
InvalidArgumentException' with message 'Unable to find image source. Valid sources are category,product,folder,content,module

Note that the error message is wrong.

The problem also exists for the document loop.

**Comment by lovenunu** [comment]
Is this fixed ?
