### ISSUE TITLE
a product without declination with a stock 0

### ISSUE THREAD

**Issue by zzuutt** [thelia/thelia#526]
a product without declination with a stock 0

![1404996927-backdispo](https://cloud.githubusercontent.com/assets/7439945/3544817/e12b1994-0870-11e4-8d10-c85c1111f317.png)

Product available is displayed in the front

![1404996963-ffrontdispo](https://cloud.githubusercontent.com/assets/7439945/3544822/ea692168-0870-11e4-8ab1-7ed67e95620f.png)

**Comment by lovenunu** [comment]
I don't when it has been fixed, but it is on master.
