### ISSUE TITLE
Exception in the install process if the admin passwords don't match

### ISSUE THREAD

**Issue by roadster31** [thelia/thelia#538]
In end.php, if the admin passwords don't match, the following error occurs : 

`ErrorException: Warning: Cannot modify header information - headers already sent by (output started at /homepages/7/d221652477/htdocs/thyno/web/install/header.php:58) in /homepages/7/d221652477/htdocs/thyno/web/install/end.php line 27`

**Comment by lovenunu** [comment]
this seems to be fixed, but another bug was related, as the header was sent but the script continued to run and created the admin.

**Comment by roadster31** [comment]
This problem is not fixed, as in `header.php`, the beginning of the page HTML code is output, starting at line 57.

Thus, it is not possible to redirect the user using `header()` in the following code, such as in line 26 of `bdd.php`.

**Comment by lunika** [comment]
Yes, the PR #1119 is still open. @lovenunu will fix it monday.
