### ISSUE TITLE
loop type="category-tree" parameter page

### ISSUE THREAD

**Issue by zzuutt** [thelia/thelia#628]
the parameters 'page' and 'depth' does not work
for test, i use
`{loop type="category-tree" name="category_list" category={category attr="id"} limit=$limit page=$category_page order=$category_order depth="1"}
 {include file="includes/single-category.html" category_id=$ID hasBtn=true hasDescription=true width="218" height="146"}
 {/loop}`

init $limit = 1
i have 3 subcategory
when page="1"
display subcategory position 2 and 3

when page="2"
display subcategory position 3

other test
the parameter 'depth' is not respected
It display all the subcategories

**Comment by bibich** [comment]
Yes it doesn't work as "excepted". 
But in fact, I don't think pagination should be used in this loop.

The best solution is to set the countable property to `false` in this loop.
