### ISSUE TITLE
Prevent deletion of default language

### ISSUE THREAD

**Issue by roadster31** [thelia/thelia#759]
If the default language is deleted, we're stuck with a RuntimeException: No default language is defined. Please define one. The back-office becomes unusable :)

If a delete language is the current back-office edition language, it is no longer possible to edit a product, category, etc., an exception is thrown.

I suppose there is a similar problem with currencies.

**Comment by neroze** [comment]
still having this is issue on fresh installation. version 2.
Fatal error: Uncaught exception 'RuntimeException' with message 'No default language is defined. Please define one.' in /Applications/XAMPP/xamppfiles/htdocs/thelia/core/lib/Thelia/Model/Lang.php:38

**Comment by neroze** [comment]
sorry working now, I guess I miss it while installing.. 
I was stucked with a RuntimeException: " No default language is defined. Please define one. "
fixed after changing by_default value to 1 for English in lang table.
