### ISSUE TITLE
apply nofilter on all URL variable in templates

### ISSUE THREAD

**Issue by lunika** [thelia/thelia#773]

**Comment by bilhackmac** [comment]
Ok to apply `nofilter` on url vars like `$admin_utilities_go_up_url` (in `templates/backOffice/default/includes/admin-utilities-position-block.html`)

But what about the smarty function url !? According to [documentation](http://doc.thelia.net/en/documentation/templates/urls-and-paths.html#noamp), you have to set `noamp=1` to escape `&` as `&amp;`, but, in fact, this is the opposite. You have to set `noamp=1` to **unescape** `&amp;` as `&`.

I think that logical in the documentation is the right way (but with the wrong term), you need more often getting url with '&' than with '&amp;'.

**Comment by bilhackmac** [comment]
Ok, I've already apply nofilter(s) with #1158
