### ISSUE TITLE
Module FreeShipping

### ISSUE THREAD

**Issue by iSkean** [thelia/thelia#776]
During the estimation of postal charges, postal charges are to 0 if the total amount of the basket exceeds the limit. However, postal charges are again paying during the choice of the mode of delivery!
**************
Pendant l'estimation des frais de port, les frais de ports sont à 0€ si le montant total du panier dépasse la limite. Cependant, les frais de port sont à nouveau payants lors du choix du mode de livraison!

**Comment by bibich** [comment]
I don't think the issue is still present in the actual module.

Please post the issue in the module page : https://github.com/thelia-modules/FreeShipping/issues

Thanks.
