### ISSUE TITLE
Too few hooks in admin templates

### ISSUE THREAD

**Issue by roadster31** [thelia/thelia#810]
In customer-edit and order-edit (and probably much more) templates , only a few hooks are defined.

We need to define more hooks in theses templates so that modules may add information on several places in the template.

**Comment by nicolasleon** [comment]
+1
Below some places where I think hooks are missing.
![product_page_desired_hooks_places](https://cloud.githubusercontent.com/assets/202879/11585017/06b8063c-9a69-11e5-966a-7866c831cc2b.png)

**Comment by gillesbourgeat** [comment]
Hello @nicolasleon,

it is possible to see the location of the hooks, by adding parameter the parameter "SHOW_HOOK" in URL.

Example : yoursite.com/index_dev.php/admin/products/update?product_id=19&SHOW_HOOK=1

```
NB : This only works in the dev environment
```

**Comment by gillesbourgeat** [comment]
@roadster31 Do you think he still lacks hooks in the BO ?

**Comment by nicolasleon** [comment]
Thanks Gilles. I think we still lack 2 hooks in the sidebar :
-1 before the default category field (product.sidebar.top ?)
-1 after the product visibility field  (product.sidebar.bottom ?)

**Comment by InformatiqueProg** [comment]
+1 for ```product.sidebar.top``` and ```product.sidebar.bottom``` in ```product-edit``` page

**Comment by roadster31** [comment]
As far as I know, we currently have no hooks inside all the update forms.
