### ISSUE TITLE
Newsletter 

### ISSUE THREAD

**Issue by zzuutt** [thelia/thelia#889]
thelia v2.0.4

on the front:
it is not possible for the visitor (not client) to unsubscribe to the newsletter

on the back:
the tool export mailing -> export only customer, no visitor

**Comment by zzuutt** [comment]
la fonction export actuelle, n'exporte que les clients avec tous les champs remplis (email, firstname, lastname)
or si le client ne s'inscrit que par le champs newsletter, il ne rentre que son email.

**Comment by gillesbourgeat** [comment]
Resolved by #2027
