### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by lunika** [thelia/thelia#946]
Some translation have disappear due to new module managing hooks. The translation is no more in the template but in the module, so we have to copy the existing translation in each modules.

**Comment by ajanssens** [comment]
Is this why there is two translations files in, by example, Hook Links module ?

I'm currently having the problem than file from i18n isn't read but in `frontOffice\default` it's correctly loaded. It results on missing the translation from `local/modules/HookLinks/I18n`

https://github.com/thelia/thelia/tree/master/local/modules/HookLinks/I18n

**Comment by roadster31** [comment]
The `local/modules/HookLinks/I18n` i18n files are module's specific translations, for the core module files, and the AdminIncludes files.

`local/modules/HookLinks/I18n/frontOffice` files are related to the frontOffice templates supported by your module. In most cases, 'default', but as a module may support more than one F.O template (or B.O, pdf, email), i18n files have to be stored in a dedicated location.

Use Thelia built-in translation tool (Configuration -> Translation), it'll make your life simpler.

**Comment by ajanssens** [comment]
Thanks @roadster31 it's clearer. Taking back my example, I have "Useful links" in my template but it's not present in `local/modules/HookLinks/I18n/frontOffice/default/fr_FR.php` so not translated.

However its present in `local/modules/HookLinks/I18n/fr_FR.php`. 

When I'm totally lost is why don't I have the translation but on the frontend demo it is working. (http://demo-v2.thelia.net/?lang=fr)

**Comment by bibich** [comment]
Fixed in #1788
