### ISSUE TITLE
Payment modules are not restricted to some currencies and/or countries

### ISSUE THREAD

**Issue by roadster31** [thelia/thelia#964]
We should provide a way to restrict the use of payment modules to some currencies and/or countries, to prevent inappropriate uses. For example a shop located in France, will not offer a payment by bank check to a foreign customer, or for non EUR currencies.

**Comment by lunika** [comment]
The stock is now managed from the module payment. I have to document it.

**Comment by roadster31** [comment]
Is stock management related to this issue ?

**Comment by lunika** [comment]
we discussed about that here, so I think yes.

**Comment by roadster31** [comment]
I don't remember what we concluded. How a french shop could prevent a swiss customer to pay by cheque ?

**Comment by lopes-vincent** [comment]
The module payment condition https://github.com/thelia-modules/PaymentCondition allow to filter payment module by area.
If we need to filter by currency we can add this feature in this module.
